import { CatalogProduct } from "../catalog";

export const BUSINESS_PRINTING_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-business-cards",
    slug: "business-cards",
    name: "Premium Business Cards",
    categorySlug: "business-printing",
    categoryName: "Business Printing",
    shortDescription: "Ultra-thick, velvet-touch visiting cards with crisp typography and optional rounded corners.",
    description: "Our Premium Business Cards are printed on sturdy 350+ GSM cardstock with rich color reproduction. Choose from luxury matte lamination, gloss finish, or soft-touch velvet coatings. Perfect for corporate founders, real estate consultants, and creative professionals.",
    basePrice: 299,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.8,
    reviewCount: 320,
    images: ["/images/prod-business-cards.jpg", "/images/cat-business-cards.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Visiting Cards", "Corporate", "Matte Finish", "Quick Dispatch"],
    sizeOptions: [
      { id: "std", label: "Standard (89 x 51 mm)", dimensions: "89 x 51 mm", multiplier: 1.0, default: true },
      { id: "square", label: "Square (65 x 65 mm)", dimensions: "65 x 65 mm", multiplier: 1.15 },
      { id: "rounded", label: "Rounded Corner Standard", dimensions: "89 x 51 mm", multiplier: 1.25 },
    ],
    materialOptions: [
      { id: "matte-350", label: "350 GSM Classic Matte", description: "Smooth anti-glare finish", extraPricePerUnit: 0, default: true },
      { id: "gloss-350", label: "350 GSM Gloss Lamination", description: "Vibrant and punchy shine", extraPricePerUnit: 0.2 },
      { id: "velvet-400", label: "400 GSM Soft-Touch Velvet", description: "Ultra-premium suede feel", extraPricePerUnit: 0.6 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 12 },
      { quantity: 500, discountPercent: 22 },
      { quantity: 1000, discountPercent: 35 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 30,
      hasFileUpload: true,
    },
    specifications: {
      "Stock Weight": "350 – 400 GSM Board",
      "Print Quality": "Indigo Digital Offset 2400 DPI",
      "Corners": "Square or 6mm Die-Cut Radius",
      "Standard Turnaround": "24 to 48 Hours",
      "Shipping": "Pan-India Courier Dispatch",
    },
    features: [
      "Precision die-cut edges with zero scuffing",
      "Fade-resistant pigmented inks",
      "Double-sided full color printing included",
      "Optional soft-touch velvet or spot UV finishes",
    ],
  },
  {
    id: "prod-letterheads",
    slug: "letterheads",
    name: "Executive Corporate Letterheads",
    categorySlug: "business-printing",
    categoryName: "Business Printing",
    shortDescription: "Laser-printer compatible executive letterheads on premium bond and textured alabaster stock.",
    description: "Make every official corporate agreement, client proposal, and legal declaration look prestigious. Guaranteed laser and inkjet feeder friendly without paper jams or ink bleeding.",
    basePrice: 499,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.7,
    reviewCount: 145,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: false,
    tags: ["Letterheads", "Stationery", "Office", "Bond Paper"],
    sizeOptions: [
      { id: "a4", label: "A4 (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.0, default: true },
      { id: "legal", label: "Legal (216 x 356 mm)", dimensions: "216 x 356 mm", multiplier: 1.2 },
    ],
    materialOptions: [
      { id: "bond-100", label: "100 GSM Executive Bond", description: "Smooth crisp paper", extraPricePerUnit: 0, default: true },
      { id: "alabaster-120", label: "120 GSM Royal Alabaster", description: "Heavy luxury texture", extraPricePerUnit: 0.5 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 10 },
      { quantity: 500, discountPercent: 20 },
      { quantity: 1000, discountPercent: 32 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 50,
      hasFileUpload: true,
    },
    specifications: {
      "Paper Stock": "100 GSM Bond / 120 GSM Alabaster",
      "Printer Compatibility": "Laser, Inkjet & Offset Safe",
      "Color Mode": "Single or Full CMYK Offset",
      "Standard Turnaround": "48 Hours",
    },
    features: [
      "Smooth glide feed for high-speed office printers",
      "Crisp micro-text reproduction for terms and fine print",
      "Acid-free archival grade for long-term records",
    ],
  },
  {
    id: "prod-envelopes",
    slug: "envelopes",
    name: "Corporate Branded Envelopes",
    categorySlug: "business-printing",
    categoryName: "Business Printing",
    shortDescription: "Custom printed peel-and-seal commercial envelopes with full-bleed flap branding.",
    description: "Deliver invoices, contracts, and marketing communications in branded envelopes that build authority before they are even opened. Features tamper-evident peel-and-seal adhesive strips.",
    basePrice: 599,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.6,
    reviewCount: 98,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: false,
    tags: ["Envelopes", "Mailing", "Corporate", "Peel and Seal"],
    sizeOptions: [
      { id: "dl", label: "DL Format (110 x 220 mm)", dimensions: "110 x 220 mm", multiplier: 1.0, default: true },
      { id: "c5", label: "C5 / A5 (162 x 229 mm)", dimensions: "162 x 229 mm", multiplier: 1.3 },
      { id: "c4", label: "C4 / A4 Document (229 x 324 mm)", dimensions: "229 x 324 mm", multiplier: 1.8 },
    ],
    materialOptions: [
      { id: "maplitho-100", label: "100 GSM White Maplitho", description: "Standard corporate white", extraPricePerUnit: 0, default: true },
      { id: "kraft-120", label: "120 GSM Eco Kraft", description: "Rustic, eco-friendly brown", extraPricePerUnit: 0.3 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 12 },
      { quantity: 500, discountPercent: 24 },
      { quantity: 1000, discountPercent: 36 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
    },
    specifications: {
      "Adhesive Type": "Super-Strong Peel & Seal Strip",
      "Print Area": "Front Face & Back Closure Flap",
      "Paper Weight": "100 – 120 GSM",
      "Standard Turnaround": "3 to 4 Business Days",
    },
    features: [
      "Instant self-adhesive strip without moisture requirement",
      "Security tint inside option prevents transparency",
      "Precision folded corners and sturdy seams",
    ],
  },
  {
    id: "prod-bill-books",
    slug: "bill-books",
    name: "Carbonless Duplicate Bill Books",
    categorySlug: "business-printing",
    categoryName: "Business Printing",
    shortDescription: "NCR carbonless bill and cash memo books with clear duplicate transfers and serial numbering.",
    description: "Essential for retail stores, repair shops, and distributors. Available in 2-ply (Duplicate: White + Yellow) and 3-ply (Triplicate: White + Pink + Yellow) with crisp serial numbering and micro-perforations.",
    basePrice: 399,
    pricingModel: "batch",
    baseQuantity: 10,
    rating: 4.8,
    reviewCount: 165,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: true,
    tags: ["Bill Books", "Cash Memo", "Carbonless", "Retail", "Invoicing"],
    sizeOptions: [
      { id: "a5", label: "A5 (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 1.0, default: true },
      { id: "a6", label: "A6 Compact (105 x 148 mm)", dimensions: "105 x 148 mm", multiplier: 0.8 },
      { id: "a4", label: "A4 Large (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.5 },
    ],
    materialOptions: [
      { id: "2-ply-ncr", label: "2-Ply Carbonless (50 Sets / Book)", description: "White top + Yellow copy", extraPricePerUnit: 0, default: true },
      { id: "3-ply-ncr", label: "3-Ply Carbonless (50 Sets / Book)", description: "White + Pink + Yellow copies", extraPricePerUnit: 25 },
    ],
    quantityTiers: [
      { quantity: 10, discountPercent: 0, default: true },
      { quantity: 25, discountPercent: 15 },
      { quantity: 50, discountPercent: 25 },
      { quantity: 100, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 40,
      hasFileUpload: true,
    },
    specifications: {
      "Sets Per Book": "50 Sets (Numbered 0001 to 0050)",
      "Binding": "Heavy Wire Stapled with Hard Cardboard Backing",
      "Perforation": "Easy Tear Micro-Perforated Top Edge",
      "Turnaround": "3 Business Days",
    },
    features: [
      "Zero carbon paper mess — modern chemical transfer",
      "Clear, legible copy through all plies",
      "Consecutive sequential numbering included free",
      "Wraparound writing shield prevents bleed-through",
    ],
  },
  {
    id: "prod-invoice-books",
    slug: "invoice-books",
    name: "Multi-Copy GST Tax Invoice Books",
    categorySlug: "business-printing",
    categoryName: "Business Printing",
    shortDescription: "Compliant multi-copy GST invoicing books with sequential numbering and wraparound covers.",
    description: "Fully compliant with Indian tax authority mandates. Tailored with your GSTIN, legal business address, state code, bank details, and terms of sale.",
    basePrice: 499,
    pricingModel: "batch",
    baseQuantity: 10,
    rating: 4.8,
    reviewCount: 110,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: false,
    tags: ["GST Invoicing", "Tax Books", "Challan", "Accounting"],
    sizeOptions: [
      { id: "a4", label: "A4 Size (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.0, default: true },
      { id: "a5", label: "A5 Compact (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 0.75 },
    ],
    materialOptions: [
      { id: "duplicate", label: "Duplicate (1+1 NCR - 50 Sets)", description: "White top + Pink duplicate", extraPricePerUnit: 0, default: true },
      { id: "triplicate", label: "Triplicate (1+2 NCR - 50 Sets)", description: "White + Pink + Yellow copies", extraPricePerUnit: 30 },
    ],
    quantityTiers: [
      { quantity: 10, discountPercent: 0, default: true },
      { quantity: 25, discountPercent: 12 },
      { quantity: 50, discountPercent: 22 },
      { quantity: 100, discountPercent: 35 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 60,
      hasFileUpload: true,
    },
    specifications: {
      "Compliance": "Indian GSTIN & HSN Code Layout",
      "Paper Weight": "55 GSM NCR Top & Bottom Sheets",
      "Cover": "Thick Laminated Kraft or Duplex Board",
      "Turnaround": "3 to 4 Business Days",
    },
    features: [
      "Tax invoice, delivery challan, or purchase order formatting",
      "Crisp sharp transfer across all sheets",
      "Strong cloth taped binding that never tears apart",
    ],
  },
  {
    id: "prod-company-profiles",
    slug: "company-profiles",
    name: "Bound Corporate Company Profiles",
    categorySlug: "business-printing",
    categoryName: "Business Printing",
    shortDescription: "High-gloss laminated corporate booklets, pitch decks, and annual capability showcases.",
    description: "Impress investors, enterprise clients, and tender committees with magazine-grade bound company profiles. Features 300 GSM card covers with satin lamination and vibrant 150 GSM art paper interior pages.",
    basePrice: 899,
    pricingModel: "batch",
    baseQuantity: 25,
    rating: 4.9,
    reviewCount: 76,
    images: ["/images/cat-brochures.jpg"],
    isFeatured: false,
    tags: ["Company Profile", "Pitch Deck", "Annual Report", "Booklet"],
    sizeOptions: [
      { id: "a4-port", label: "A4 Portrait (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.0, default: true },
      { id: "a4-land", label: "A4 Landscape (297 x 210 mm)", dimensions: "297 x 210 mm", multiplier: 1.2 },
    ],
    materialOptions: [
      { id: "saddle-8p", label: "8 Pages (Saddle Stitch)", description: "Folded and dual center stapled", extraPricePerUnit: 0, default: true },
      { id: "saddle-16p", label: "16 Pages (Saddle Stitch)", description: "High-capacity presentation", extraPricePerUnit: 15 },
      { id: "perfect-24p", label: "24 Pages (Perfect Spine Bound)", description: "Square spine book style", extraPricePerUnit: 35 },
    ],
    quantityTiers: [
      { quantity: 25, discountPercent: 0, default: true },
      { quantity: 50, discountPercent: 15 },
      { quantity: 100, discountPercent: 28 },
      { quantity: 250, discountPercent: 40 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
    },
    specifications: {
      "Cover Weight": "300 GSM Art Card with Thermal Matte/Gloss",
      "Inner Sheets": "150 GSM Imported Gloss Art Paper",
      "Binding": "Precision Saddle-Stitch or Polyurethane Perfect Bound",
      "Turnaround": "3 to 5 Business Days",
    },
    features: [
      "HD photographic clarity for architecture, manufacturing, and tech",
      "Spot UV and gold foil options available for front logo",
      "Creased hinges for smooth lay-flat opening",
    ],
  },
];
