import { CatalogProduct } from "../catalog";

export const LABELS_STICKERS_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-stickers",
    slug: "custom-stickers",
    name: "Waterproof Die-Cut Vinyl Logo Stickers",
    categorySlug: "labels-stickers",
    categoryName: "Labels & Stickers",
    shortDescription: "Custom precision cut individual vinyl stickers with UV-resistant glossy or matte laminate.",
    description: "Print custom die-cut vinyl stickers contoured exactly to the shape of your artwork. Weatherproof, dishwasher safe, and scratch-resistant for laptops, water bottles, skateboards, and helmets.",
    basePrice: 349,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.9,
    reviewCount: 340,
    images: ["/images/prod-stickers.jpg", "/images/cat-stickers.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Stickers", "Die-Cut", "Vinyl", "Waterproof", "Laptop Stickers"],
    sizeOptions: [
      { id: "stk-2in", label: "2 x 2 Inches (50 x 50 mm)", dimensions: "50 x 50 mm", multiplier: 1.0, default: true },
      { id: "stk-3in", label: "3 x 3 Inches (75 x 75 mm)", dimensions: "75 x 75 mm", multiplier: 1.45 },
      { id: "stk-4in", label: "4 x 4 Inches (100 x 100 mm)", dimensions: "100 x 100 mm", multiplier: 1.95 },
    ],
    materialOptions: [
      { id: "vin-white-gloss", label: "Premium White Vinyl (Gloss Lamination)", description: "Vibrant high-contrast shine", extraPricePerUnit: 0, default: true },
      { id: "vin-white-matte", label: "Premium White Vinyl (Velvet Matte Lamination)", description: "Soft anti-glare aesthetic", extraPricePerUnit: 0.1 },
      { id: "vin-holographic", label: "Rainbow Holographic Vinyl Base", description: "Shimmers with iridescent colors under light", extraPricePerUnit: 0.75 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 15 },
      { quantity: 500, discountPercent: 28 },
      { quantity: 1000, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "Upload vector PDF/PNG with transparent background. Cut-line will be generated automatically.",
    },
    specifications: {
      "Film Thickness": "120 Micron Monomeric Calendered Vinyl",
      "Lamination": "Outdoor-Grade UV Cold Overlaminate",
      "Water Resistance": "100% Dishwasher, Rain, and UV Sun Proof",
      "Peel Backing": "Thick silicone-coated release liner with easy-peel border",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "Custom laser contour cutting hugs every curve of your illustration or typography",
      "Heavy laminate prevents scratches, sun fading, and peeling",
      "Peels off cleanly leaving zero sticky adhesive residue",
    ],
  },
  {
    id: "prod-bottle-labels",
    slug: "bottle-labels",
    name: "Moisture-Resistant Roll Bottle & Jar Labels",
    categorySlug: "labels-stickers",
    categoryName: "Labels & Stickers",
    shortDescription: "Waterproof roll labels for cosmetics, beverage bottles, glass jars, and food containers.",
    description: "Engineered to withstand condensation, refrigerator cooling, oil drips, and handling friction. Supplied on standardized cardboard rolls compatible with automated or manual label dispensers.",
    basePrice: 499,
    pricingModel: "batch",
    baseQuantity: 250,
    rating: 4.8,
    reviewCount: 125,
    images: ["/images/cat-stickers.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Bottle Labels", "Jar Labels", "Roll Labels", "Waterproof", "Cosmetics"],
    sizeOptions: [
      { id: "lbl-rec-small", label: "Compact Jar (50 x 75 mm)", dimensions: "50 x 75 mm", multiplier: 1.0, default: true },
      { id: "lbl-rec-bottle", label: "Wine / Beverage Bottle (75 x 100 mm)", dimensions: "75 x 100 mm", multiplier: 1.35 },
      { id: "lbl-round-jar", label: "Round Lid Seal (60 mm Dia)", dimensions: "60 mm circle", multiplier: 1.1 },
    ],
    materialOptions: [
      { id: "pp-white-waterproof", label: "White BOPP Plastic Film (Gloss Laminate)", description: "Impervious to water, oil, and refrigeration", extraPricePerUnit: 0, default: true },
      { id: "kraft-textured-label", label: "Uncoated Textured Estate Wine Paper", description: "Artisanal vintage organic look", extraPricePerUnit: 0.35 },
    ],
    quantityTiers: [
      { quantity: 250, discountPercent: 0, default: true },
      { quantity: 500, discountPercent: 18 },
      { quantity: 1000, discountPercent: 32 },
      { quantity: 2500, discountPercent: 48 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
    },
    specifications: {
      "Core Size": "Standard 3-inch (76 mm) inner cardboard core",
      "Dispensing": "Machine application or hand peel orientation 4 (Left edge leading)",
      "Adhesive": "FDA food contact compliant emulsion acrylic permanent glue",
      "Turnaround": "3 to 4 Business Days",
    },
    features: [
      "Will not wrinkle, bubble, or detach when submerged in ice buckets",
      "Resistant to essential oils, detergents, and food sauces",
      "Perfect roll tension ensures zero jams during automatic machine labelling",
    ],
  },
  {
    id: "prod-barcode-labels",
    slug: "barcode-labels",
    name: "Thermal Barcode & Asset QR Labels",
    categorySlug: "labels-stickers",
    categoryName: "Labels & Stickers",
    shortDescription: "High-contrast thermal transfer barcode, SKU, and asset tracking roll labels.",
    description: "Ensure error-free logistics, warehouse fulfillment, and retail POS checkout scanning. Printed with smudge-free resin ribbons on premium thermal paper or polyester stock.",
    basePrice: 399,
    pricingModel: "batch",
    baseQuantity: 1000,
    rating: 4.7,
    reviewCount: 92,
    images: ["/images/cat-stickers.jpg"],
    isFeatured: false,
    tags: ["Barcode", "QR Code", "Inventory", "Asset Tag", "Warehouse"],
    sizeOptions: [
      { id: "bar-50x25", label: "50 x 25 mm (2 x 1 in)", dimensions: "50 x 25 mm", multiplier: 1.0, default: true },
      { id: "bar-50x38", label: "50 x 38 mm (2 x 1.5 in)", dimensions: "50 x 38 mm", multiplier: 1.25 },
      { id: "bar-100x50", label: "100 x 50 mm (4 x 2 in Shipping)", dimensions: "100 x 50 mm", multiplier: 1.8 },
    ],
    materialOptions: [
      { id: "tt-chromo", label: "Chromo Paper (Wax-Resin Printed)", description: "High contrast for retail packaging", extraPricePerUnit: 0, default: true },
      { id: "tt-poly", label: "Silver Matt Polyester (Indelible Resin)", description: "Scuff-proof asset tracking for machinery and IT equipment", extraPricePerUnit: 0.25 },
    ],
    quantityTiers: [
      { quantity: 1000, discountPercent: 0, default: true },
      { quantity: 2500, discountPercent: 12 },
      { quantity: 5000, discountPercent: 24 },
      { quantity: 10000, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 20,
      hasFileUpload: true,
      uploadInstructions: "Send barcode symbology (Code 128, EAN-13, QR) and sequential numbering range.",
    },
    specifications: {
      "Symbology": "Code 128, Code 39, EAN-13, UPC-A, DataMatrix, QR Code",
      "Scanner Grade": "Grade A verification score with 600 DPI edge sharpness",
      "Adhesive": "Permanent high-tack rubber/acrylic",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "100% first-pass read rate on handheld and conveyor optical scanners",
      "Smudge-proof resin ribbon resists abrasion during shipping transit",
      "Supplied on universal rolls compatible with Zebra, TSC, and Argox printers",
    ],
  },
  {
    id: "prod-transparent-stickers",
    slug: "transparent-stickers",
    name: "Clear Transparent Adhesive Vinyl Decals",
    categorySlug: "labels-stickers",
    categoryName: "Labels & Stickers",
    shortDescription: "Ultra-clear see-through vinyl stickers printed with opaque white ink underlays.",
    description: "Achieve an invisible, printed-directly-on-glass look. Printed with advanced UV flatbed technology featuring opaque white base layers to ensure colors remain bright even on dark or clear substrates.",
    basePrice: 399,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.8,
    reviewCount: 88,
    images: ["/images/cat-stickers.jpg", "/images/prod-stickers.jpg"],
    isFeatured: false,
    tags: ["Clear Stickers", "Transparent", "Window Decal", "White Ink"],
    sizeOptions: [
      { id: "clr-2in", label: "2 x 2 Inches (50 x 50 mm)", dimensions: "50 x 50 mm", multiplier: 1.0, default: true },
      { id: "clr-3in", label: "3 x 3 Inches (75 x 75 mm)", dimensions: "75 x 75 mm", multiplier: 1.4 },
      { id: "clr-4in", label: "4 x 4 Inches (100 x 100 mm)", dimensions: "100 x 100 mm", multiplier: 1.9 },
    ],
    materialOptions: [
      { id: "clr-gloss", label: "Ultra-Clear Gloss Polyester Film", description: "Completely transparent crystal look", extraPricePerUnit: 0, default: true },
      { id: "clr-frosted", label: "Frosted Translucent Vinyl", description: "Subtle sandblast privacy effect", extraPricePerUnit: 0.2 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 12 },
      { quantity: 500, discountPercent: 24 },
      { quantity: 1000, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "Transparent PNG with vector paths. Indicate if white ink backup is desired.",
    },
    specifications: {
      "Substrate": "Optically Clear 80 Micron PET / PVC Film",
      "Underlay": "High-density white ink printing prevents artwork from looking washed out",
      "Outdoor Lifespan": "Up to 2 years UV stability",
      "Turnaround": "48 Hours",
    },
    features: [
      "Gives products a luxury 'no-label' direct screenprint appearance",
      "White ink backup layer prevents background colors from showing through",
      "Weatherproof adhesive adheres smoothly to glassware, acrylic, and mirrors",
    ],
  },
  {
    id: "prod-custom-diecut-stickers",
    slug: "custom-shape-stickers",
    name: "Custom Shape Kiss-Cut Sticker Sheets",
    categorySlug: "labels-stickers",
    categoryName: "Labels & Stickers",
    shortDescription: "A4 and A5 multiple sticker sheets with kiss-cut peelable shapes on a single backing.",
    description: "Pack multiple illustrations, branding icons, and fun characters onto a single organized sheet. Ideal for promotional giveaway packs, event swag bags, and software brand merch.",
    basePrice: 449,
    pricingModel: "batch",
    baseQuantity: 50,
    rating: 4.9,
    reviewCount: 108,
    images: ["/images/prod-stickers.jpg"],
    isFeatured: false,
    tags: ["Sticker Sheet", "Kiss-Cut", "Merchandise", "Planner Stickers"],
    sizeOptions: [
      { id: "sheet-a5", label: "A5 Sheet (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 1.0, default: true },
      { id: "sheet-a4", label: "A4 Sheet (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.6 },
    ],
    materialOptions: [
      { id: "sheet-vinyl-gloss", label: "Gloss Laminated Vinyl Sheet", description: "Vibrant colors, water resistant", extraPricePerUnit: 0, default: true },
      { id: "sheet-paper-matte", label: "Writable Matte Paper Sticker Sheet", description: "Easy to write on for planners & journals", extraPricePerUnit: -0.1 },
    ],
    quantityTiers: [
      { quantity: 50, discountPercent: 0, default: true },
      { quantity: 100, discountPercent: 15 },
      { quantity: 250, discountPercent: 28 },
      { quantity: 500, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "Keep 2mm spacing between individual kiss-cut shapes on the sheet.",
    },
    specifications: {
      "Cutting Tech": "Digital CNC Drag-Knife Kiss-Cutting (Cuts vinyl layer only, leaving liner intact)",
      "Shapes per Sheet": "Typically 6 to 15 peelable stickers per sheet",
      "Liner": "Heavy 140 GSM lay-flat release paper",
      "Turnaround": "48 Hours",
    },
    features: [
      "Stickers peel smoothly from the master sheet without tearing",
      "Lay-flat backing sheet will not curl under atmospheric humidity",
      "Print additional branding and instructions on the sheet borders",
    ],
  },
  {
    id: "prod-holographic-stickers",
    slug: "holographic-stickers",
    name: "Security Holographic Anti-Counterfeit Stickers",
    categorySlug: "labels-stickers",
    categoryName: "Labels & Stickers",
    shortDescription: "Laser rainbow holographic security seals with tamper-evident honeycomb breakage.",
    description: "Protect brand authenticity and warrant product warranties. Metallic holographic diffractions shine with dynamic 3D depth and destruct upon unauthorized removal attempts.",
    basePrice: 699,
    pricingModel: "batch",
    baseQuantity: 250,
    rating: 4.8,
    reviewCount: 76,
    images: ["/images/cat-stickers.jpg"],
    isFeatured: false,
    tags: ["Hologram", "Security Seal", "Tamper Evident", "Warranty Sticker", "Authentic"],
    sizeOptions: [
      { id: "holo-20mm", label: "20 mm Round Coin", dimensions: "20 mm diameter", multiplier: 1.0, default: true },
      { id: "holo-25mm", label: "25 mm Square (1 x 1 in)", dimensions: "25 x 25 mm", multiplier: 1.25 },
      { id: "holo-rec", label: "35 x 15 mm Rectangle Warranty Strip", dimensions: "35 x 15 mm", multiplier: 1.15 },
    ],
    materialOptions: [
      { id: "holo-destruct", label: "Tamper-Destructive Honeycomb Foil", description: "Breaks into honeycomb pattern if peeled", extraPricePerUnit: 0, default: true },
      { id: "holo-standard", label: "Non-Destructive Iridescent Rainbow Film", description: "Eye-catching shimmer for product packaging", extraPricePerUnit: -0.2 },
    ],
    quantityTiers: [
      { quantity: 250, discountPercent: 0, default: true },
      { quantity: 500, discountPercent: 15 },
      { quantity: 1000, discountPercent: 28 },
      { quantity: 2500, discountPercent: 44 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 25,
      hasFileUpload: true,
    },
    specifications: {
      "Security Layer": "2D/3D Optical Kinetic Diffraction Master",
      "Destruction": "Self-destructs instantly when lifted from packaging",
      "Serialization": "Unique laser-etched black or transparent serial numbering",
      "Turnaround": "4 to 5 Business Days",
    },
    features: [
      "Impossible to replicate with standard photocopiers or home printers",
      "Tamper-evident pattern proves whether box has been opened before purchase",
      "Sequentially laser numbered for warranty registry tracking",
    ],
  },
];
