import { CatalogProduct } from "../catalog";

export const MARKETING_MATERIALS_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-a4-flyers",
    slug: "a4-flyers",
    name: "A4 Marketing Flyers",
    categorySlug: "marketing-materials",
    categoryName: "Marketing Materials",
    shortDescription: "High-volume promotional flyers with vivid photographic fidelity on coated art paper.",
    description: "Drive foot traffic and sales conversions with crisp, vibrant full-color flyers. Ideal for retail promotional campaigns, restaurant menus, event handouts, and real estate showcases.",
    basePrice: 499,
    pricingModel: "batch",
    baseQuantity: 250,
    rating: 4.8,
    reviewCount: 188,
    images: ["/images/prod-flyers.jpg", "/images/cat-flyers.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Flyers", "Leaflets", "Marketing", "Bulk Promotion"],
    sizeOptions: [
      { id: "a4", label: "A4 (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.0, default: true },
      { id: "a5", label: "A5 Half Size (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 0.65 },
      { id: "a6", label: "A6 Postcard (105 x 148 mm)", dimensions: "105 x 148 mm", multiplier: 0.45 },
    ],
    materialOptions: [
      { id: "art-130", label: "130 GSM Gloss Art Paper", description: "Lightweight promotional handbill", extraPricePerUnit: 0, default: true },
      { id: "art-170", label: "170 GSM Premium Gloss Art Paper", description: "Substantial hand feel, zero show-through", extraPricePerUnit: 0.35 },
      { id: "card-250", label: "250 GSM Sturdy Cardstock", description: "Rigid luxury handout with velvet coat", extraPricePerUnit: 0.75 },
    ],
    quantityTiers: [
      { quantity: 250, discountPercent: 0, default: true },
      { quantity: 500, discountPercent: 18 },
      { quantity: 1000, discountPercent: 32 },
      { quantity: 2500, discountPercent: 45 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 40,
      hasFileUpload: true,
      uploadInstructions: "High-res PDF/AI at 300 DPI with 3mm bleed.",
    },
    specifications: {
      "Dimensions": "210 x 297 mm (A4 standard)",
      "Print Tech": "Komori 4-Color High-Speed Offset",
      "Coating": "Protective Aqueous Gloss or Matte Varnish",
      "Turnaround": "24 to 48 Hours",
      "Bleed Margin": "3 mm safety trim zone",
    },
    features: [
      "Rich CMYK color saturation for food, fashion, and retail",
      "Double-sided edge-to-edge full bleed printing",
      "Precision computerized knife trimming",
      "Express bulk dispatch across India",
    ],
  },
  {
    id: "prod-brochures",
    slug: "brochures",
    name: "Tri-Fold & Bi-Fold Brochures",
    categorySlug: "marketing-materials",
    categoryName: "Marketing Materials",
    shortDescription: "Creased, multi-panel marketing brochures for comprehensive product guides and menus.",
    description: "Give your potential clients a structured journey through your services. Our precision-scored brochures fold cleanly without cracking along spine creases, utilizing premium coated art paper.",
    basePrice: 599,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.9,
    reviewCount: 142,
    images: ["/images/cat-brochures.jpg", "/images/prod-flyers.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Brochures", "Tri-Fold", "Pamphlets", "Menus"],
    sizeOptions: [
      { id: "trifold-a4", label: "A4 Tri-Fold (Folded to 100 x 210 mm)", dimensions: "Open 297 x 210 mm", multiplier: 1.0, default: true },
      { id: "bifold-a4", label: "A4 Bi-Fold (Folded to 148 x 210 mm)", dimensions: "Open 297 x 210 mm", multiplier: 1.0 },
      { id: "trifold-a3", label: "A3 Tri-Fold Large (Folded to 140 x 297 mm)", dimensions: "Open 420 x 297 mm", multiplier: 1.65 },
    ],
    materialOptions: [
      { id: "art-170", label: "170 GSM Silk Finish Art Paper", description: "Smooth anti-glare reading texture", extraPricePerUnit: 0, default: true },
      { id: "art-250", label: "250 GSM Premium Cardstock", description: "Heavy card with thermal matte film", extraPricePerUnit: 0.6 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 15 },
      { quantity: 500, discountPercent: 28 },
      { quantity: 1000, discountPercent: 40 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "Include 3mm bleed on all sides. Specify fold orientation.",
    },
    specifications: {
      "Fold Styles": "Letter Tri-Fold, Z-Fold, Gate-Fold, Half Bi-Fold",
      "Scoring": "Pre-creased on automated Morgana creaser",
      "Ink System": "Direct Dry Eco-friendly Offset Inks",
      "Turnaround": "48 Hours",
    },
    features: [
      "Six organized informational panels for deep storytelling",
      "Zero toner cracking along fold lines",
      "Smooth velvet or gloss exterior coatings",
      "Pre-assembled and flat-bundled in moisture barrier wrappers",
    ],
  },
  {
    id: "prod-leaflets",
    slug: "leaflets",
    name: "Handout Promotional Leaflets",
    categorySlug: "marketing-materials",
    categoryName: "Marketing Materials",
    shortDescription: "Economical, lightweight handout leaflets for massive door-to-door and street distribution.",
    description: "Designed for high-impact neighborhood marketing, trade show handouts, and coupon drops. Deliver clear calls to action with cost-effective bulk printing.",
    basePrice: 449,
    pricingModel: "batch",
    baseQuantity: 500,
    rating: 4.7,
    reviewCount: 96,
    images: ["/images/cat-flyers.jpg"],
    isFeatured: false,
    tags: ["Leaflets", "Handouts", "Door Drop", "Mass Campaign"],
    sizeOptions: [
      { id: "a5", label: "A5 Standard (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 1.0, default: true },
      { id: "a6", label: "A6 Pocket (105 x 148 mm)", dimensions: "105 x 148 mm", multiplier: 0.7 },
      { id: "dl", label: "DL Slim (99 x 210 mm)", dimensions: "99 x 210 mm", multiplier: 0.8 },
    ],
    materialOptions: [
      { id: "art-90", label: "90 GSM Economy Gloss Paper", description: "Cost-effective high-volume paper", extraPricePerUnit: 0, default: true },
      { id: "art-130", label: "130 GSM Standard Gloss Paper", description: "Crisp handbill feel", extraPricePerUnit: 0.2 },
    ],
    quantityTiers: [
      { quantity: 500, discountPercent: 0, default: true },
      { quantity: 1000, discountPercent: 18 },
      { quantity: 2500, discountPercent: 32 },
      { quantity: 5000, discountPercent: 48 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 30,
      hasFileUpload: true,
    },
    specifications: {
      "Print Sides": "Single or Double Sided Full Color",
      "Paper Stock": "90 – 130 GSM Bright White Art",
      "Packaging": "Banded in stacks of 100 in corrugated cartons",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "Maximum impressions per rupee spent",
      "Vibrant full color front and back",
      "Lightweight for economical postal drops and courier delivery",
    ],
  },
  {
    id: "prod-posters",
    slug: "posters",
    name: "High-Gloss Promotional Posters",
    categorySlug: "marketing-materials",
    categoryName: "Marketing Materials",
    shortDescription: "Vibrant large-format A3 & A2 posters for store windows, club events, and movie releases.",
    description: "Capture attention across hallways, storefronts, and campuses. Printed with UV-curable inks on heavy 250 GSM satin paper for outstanding color saturation and contrast.",
    basePrice: 399,
    pricingModel: "batch",
    baseQuantity: 25,
    rating: 4.8,
    reviewCount: 84,
    images: ["/images/cat-brochures.jpg", "/images/prod-flyers.jpg"],
    isFeatured: false,
    tags: ["Posters", "Wall Art", "Event Promotion", "Storefront"],
    sizeOptions: [
      { id: "a3", label: "A3 (297 x 420 mm)", dimensions: "297 x 420 mm", multiplier: 1.0, default: true },
      { id: "a2", label: "A2 (420 x 594 mm)", dimensions: "420 x 594 mm", multiplier: 1.8 },
      { id: "a1", label: "A1 Mega (594 x 841 mm)", dimensions: "594 x 841 mm", multiplier: 3.2 },
    ],
    materialOptions: [
      { id: "art-200", label: "200 GSM Heavy Photo Gloss", description: "Vivid, reflective colors", extraPricePerUnit: 0, default: true },
      { id: "matte-250", label: "250 GSM Anti-Glare Matte Board", description: "No glare under indoor gallery lighting", extraPricePerUnit: 0.4 },
    ],
    quantityTiers: [
      { quantity: 25, discountPercent: 0, default: true },
      { quantity: 50, discountPercent: 15 },
      { quantity: 100, discountPercent: 28 },
      { quantity: 250, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "300 DPI minimum resolution recommended for large scale.",
    },
    specifications: {
      "Print Tech": "Wide-Format High Dynamic Range Pigment Inks",
      "Resistance": "Indoor fade resistant for up to 3 years",
      "Packaging": "Rolled in heavy kraft tubes or flat packed with cardboard inserts",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "Photo-grade detail for complex photography and artwork",
      "Heavy stock resists curling and waving in humid weather",
      "True deep blacks and vivid neon-like color gamuts",
    ],
  },
  {
    id: "prod-pamphlets",
    slug: "pamphlets",
    name: "Newspaper Insert & Door Pamphlets",
    categorySlug: "marketing-materials",
    categoryName: "Marketing Materials",
    shortDescription: "Ultra-cost-efficient printed pamphlets designed for morning newspaper inserts and local launches.",
    description: "The gold standard for hyper-local retail, coaching institutes, grocery stores, and healthcare clinics. Reach every household in your target pin codes with crisp newspaper insertions.",
    basePrice: 699,
    pricingModel: "batch",
    baseQuantity: 1000,
    rating: 4.6,
    reviewCount: 130,
    images: ["/images/cat-flyers.jpg"],
    isFeatured: false,
    tags: ["Pamphlets", "Newspaper Insert", "Hyperlocal", "Direct Marketing"],
    sizeOptions: [
      { id: "pam-a5", label: "A5 (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 1.0, default: true },
      { id: "pam-a4", label: "A4 (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.5 },
    ],
    materialOptions: [
      { id: "map-70", label: "70 GSM Maplitho White Paper", description: "Standard newspaper insert paper", extraPricePerUnit: 0, default: true },
      { id: "art-100", label: "100 GSM Light Coated Art", description: "Vibrant look without heavy weight", extraPricePerUnit: 0.15 },
    ],
    quantityTiers: [
      { quantity: 1000, discountPercent: 0, default: true },
      { quantity: 2500, discountPercent: 15 },
      { quantity: 5000, discountPercent: 28 },
      { quantity: 10000, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 50,
      hasFileUpload: true,
    },
    specifications: {
      "Paper": "70 GSM Maplitho / 100 GSM Light Art",
      "Colorway": "Double Sided 4-Color Process",
      "Standard Delivery": "Stacked in bundles of 500",
      "Turnaround": "48 Hours",
    },
    features: [
      "Optimized weight for quick morning newspaper insertion",
      "Smear-resistant high-speed web/sheetfed offset printing",
      "Lowest cost per distributed household",
    ],
  },
  {
    id: "prod-catalogues",
    slug: "catalogues",
    name: "Multi-Page Product Catalogues",
    categorySlug: "marketing-materials",
    categoryName: "Marketing Materials",
    shortDescription: "Stapled & spine-bound commercial catalogues with high-density product grids and pricing.",
    description: "Provide wholesalers, retail distributors, and procurement teams with a complete tactile compendium of your SKU range. Finished with scratch-resistant thermal lamination.",
    basePrice: 1299,
    pricingModel: "batch",
    baseQuantity: 25,
    rating: 4.9,
    reviewCount: 62,
    images: ["/images/cat-brochures.jpg"],
    isFeatured: false,
    tags: ["Catalogues", "Product Guides", "Wholesale", "Booklets"],
    sizeOptions: [
      { id: "cat-a4", label: "A4 Portrait (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.0, default: true },
      { id: "cat-a5", label: "A5 Compact (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 0.8 },
    ],
    materialOptions: [
      { id: "cat-16p", label: "16 Pages (300 GSM Cover + 150 GSM Art)", description: "Center wire stitched", extraPricePerUnit: 0, default: true },
      { id: "cat-32p", label: "32 Pages (300 GSM Cover + 130 GSM Art)", description: "Extended catalog range", extraPricePerUnit: 25 },
      { id: "cat-48p", label: "48 Pages (Square Spine Bound)", description: "Full enterprise line", extraPricePerUnit: 55 },
    ],
    quantityTiers: [
      { quantity: 25, discountPercent: 0, default: true },
      { quantity: 50, discountPercent: 12 },
      { quantity: 100, discountPercent: 25 },
      { quantity: 250, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "Provide single-page PDF in chronological order with 3mm bleed.",
    },
    specifications: {
      "Cover Finish": "Velvet Matte or High Gloss Thermal Lamination",
      "Binding": "Heavy Wire Saddle-Stitch or EVA Perfect Bind",
      "Paper": "130 – 150 GSM Imported Hi-Brite Art Paper",
      "Turnaround": "4 to 6 Business Days",
    },
    features: [
      "Consistent color density across all product photography",
      "Heavy duty binding holds up to repeated showroom browsing",
      "Barcode, SKU, and specifications table layout proofing",
    ],
  },
];
