import { CatalogProduct } from "../catalog";

export const OUTDOOR_ADVERTISING_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-flex-printing",
    slug: "flex-printing",
    name: "Heavy-Duty Frontlit Flex Printing",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Weatherproof solvent-printed PVC flex banners for outdoor promotions and temporary shop hoardings.",
    description: "Our commercial-grade frontlit flex banners withstand harsh sunlight, monsoons, and highway winds. Printed with high-density outdoor eco-solvent inks for maximum vibrancy.",
    basePrice: 249,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.7,
    reviewCount: 165,
    images: ["/images/cat-banners.jpg", "/images/prod-banner.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Flex Banner", "Frontlit", "Outdoor Advertising", "Waterproof"],
    sizeOptions: [
      { id: "flex-6x3", label: "6 x 3 Feet (18 sq ft)", dimensions: "182 x 91 cm", multiplier: 1.0, default: true },
      { id: "flex-8x4", label: "8 x 4 Feet (32 sq ft)", dimensions: "243 x 121 cm", multiplier: 1.7 },
      { id: "flex-10x5", label: "10 x 5 Feet (50 sq ft)", dimensions: "304 x 152 cm", multiplier: 2.6 },
      { id: "flex-12x6", label: "12 x 6 Feet (72 sq ft)", dimensions: "365 x 182 cm", multiplier: 3.8 },
    ],
    materialOptions: [
      { id: "flex-normal", label: "Normal Flex (240 GSM)", description: "Cost-effective for short campaigns", extraPricePerUnit: 0, default: true },
      { id: "flex-star", label: "Star / Blackout Flex (340 GSM)", description: "Heavy-duty tear-resistant with dark backing", extraPricePerUnit: 120 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 3, discountPercent: 10 },
      { quantity: 5, discountPercent: 18 },
      { quantity: 10, discountPercent: 28 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 60,
      hasFileUpload: true,
      uploadInstructions: "72 to 150 DPI at actual size in CMYK format.",
    },
    specifications: {
      "GSM Weight": "240 – 340 GSM PVC Flex",
      "Print Tech": "Seiko / Konica Minolta Eco-Solvent Head",
      "Edge Finishing": "Thermal welded hem edges with brass grommets every 2 feet",
      "Outdoor Lifespan": "12 to 24 Months UV Stability",
      "Turnaround": "24 Hours",
    },
    features: [
      "Heavy-duty heat-welded seams prevent fraying in high winds",
      "Rust-proof brass grommets for easy rope/cable-tie installation",
      "Zero color fading under harsh tropical sunshine",
    ],
  },
  {
    id: "prod-vinyl-banner",
    slug: "vinyl-banners",
    name: "Premium Outdoor Vinyl Banners",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Heavyweight tear-resistant vinyl banners with reinforced hems and metal grommets.",
    description: "Built for long-term outdoor exhibition, construction site perimeters, festival entrances, and sports arenas. Printed with UV-curable inks that resist rain, abrasions, and extreme weather.",
    basePrice: 349,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 142,
    images: ["/images/prod-banner.jpg", "/images/cat-banners.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Vinyl Banner", "Weatherproof", "Large Format", "Grommets"],
    sizeOptions: [
      { id: "v-4x2", label: "4 x 2 Feet (Compact)", dimensions: "120 x 60 cm", multiplier: 1.0, default: true },
      { id: "v-6x3", label: "6 x 3 Feet (Standard)", dimensions: "180 x 90 cm", multiplier: 1.6 },
      { id: "v-8x4", label: "8 x 4 Feet (Promotional)", dimensions: "240 x 120 cm", multiplier: 2.5 },
      { id: "v-10x4", label: "10 x 4 Feet (Grand)", dimensions: "300 x 120 cm", multiplier: 3.2 },
    ],
    materialOptions: [
      { id: "vinyl-440", label: "440 GSM Matte Vinyl", description: "Non-glare matte for photography", extraPricePerUnit: 0, default: true },
      { id: "vinyl-510", label: "510 GSM Heavy Scrim Vinyl", description: "Max tensile tear resistance", extraPricePerUnit: 140 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 10 },
      { quantity: 5, discountPercent: 20 },
      { quantity: 10, discountPercent: 32 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 50,
      hasFileUpload: true,
    },
    specifications: {
      "Substrate": "440 – 510 GSM High Tenacity Scrim Vinyl",
      "Grommets": "Nickel-plated anti-rust eyelets every 50 cm",
      "Ink Chemistry": "True UV-Curable Pigment Inks",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "Engineered for outdoor durability in tropical climates",
      "Includes welded perimeter hem for extra tensile strength",
      "Easy rollup storage without creasing",
    ],
  },
  {
    id: "prod-hanging-banners",
    slug: "hanging-banners",
    name: "Ceiling & Pole Hanging Banners",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Suspended double-sided street pole banners and indoor atrium hanging banners with pole pockets.",
    description: "Command eye-level attention on boulevard lampposts, shopping malls, and exhibition atriums. Fitted with top and bottom aluminium dowels or stitched pole sleeves.",
    basePrice: 499,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 54,
    images: ["/images/cat-banners.jpg"],
    isFeatured: false,
    tags: ["Hanging Banner", "Pole Banner", "Mall Branding", "Double Sided"],
    sizeOptions: [
      { id: "hang-4x2", label: "4 x 2 Feet (Vertical)", dimensions: "60 x 120 cm", multiplier: 1.0, default: true },
      { id: "hang-6x2", label: "6 x 2.5 Feet (Street Pole)", dimensions: "75 x 180 cm", multiplier: 1.6 },
      { id: "hang-8x3", label: "8 x 3 Feet (Atrium Banner)", dimensions: "90 x 240 cm", multiplier: 2.4 },
    ],
    materialOptions: [
      { id: "single-pole", label: "Single-Sided Blockout Fabric", description: "Lightweight draped fabric", extraPricePerUnit: 0, default: true },
      { id: "double-pole", label: "Double-Sided 600 GSM Opaque Vinyl", description: "Zero light bleed between faces", extraPricePerUnit: 220 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 4, discountPercent: 12 },
      { quantity: 10, discountPercent: 22 },
      { quantity: 20, discountPercent: 35 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
    },
    specifications: {
      "Finishing": "3-inch top and bottom pole pockets with weighted inserts",
      "Wind Rating": "Tested up to 45 km/h with optional wind slits",
      "Print": "Double-sided identical or distinct artwork",
      "Turnaround": "48 Hours",
    },
    features: [
      "Weighted hem bars prevent curling and keep banner taut",
      "Complete blackout barrier layer prevents show-through",
      "Compatible with standard city street-pole bracket systems",
    ],
  },
  {
    id: "prod-hoardings",
    slug: "hoardings",
    name: "Mega Outdoor Billboard & Hoarding Flex",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Ultra-wide seamless hoarding flex skins for highway billboards and commercial building wraps.",
    description: "Engineered specifically for mega outdoor billboards, skywalk gantries, and construction barricades. Printed on industrial super-wide format engines with superior contrast visible from hundreds of meters.",
    basePrice: 1499,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.9,
    reviewCount: 38,
    images: ["/images/cat-banners.jpg"],
    isFeatured: false,
    tags: ["Billboard", "Hoarding", "Mega Signage", "Highway"],
    sizeOptions: [
      { id: "board-20x10", label: "20 x 10 Feet (200 sq ft)", dimensions: "6 x 3 meters", multiplier: 1.0, default: true },
      { id: "board-30x15", label: "30 x 15 Feet (450 sq ft)", dimensions: "9 x 4.5 meters", multiplier: 2.2 },
      { id: "board-40x20", label: "40 x 20 Feet (800 sq ft)", dimensions: "12 x 6 meters", multiplier: 3.8 },
    ],
    materialOptions: [
      { id: "star-380", label: "Star Frontlit 380 GSM Flex", description: "Standard high tensile billboard flex", extraPricePerUnit: 0, default: true },
      { id: "blackout-500", label: "500 GSM Heavy Black Backing", description: "Blocks structure shadows behind skin", extraPricePerUnit: 450 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 8 },
      { quantity: 4, discountPercent: 15 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "30 to 50 DPI at 1:1 scale or 300 DPI at 1:10 scale.",
    },
    specifications: {
      "Maximum Seamless Width": "Up to 5 meters (16.4 ft) without joint seams",
      "Joint Technique": "High frequency ultrasonic RF welding for oversized panels",
      "Wind Loads": "Engineered for high velocity highway conditions",
      "Turnaround": "48 to 72 Hours",
    },
    features: [
      "Ultra-wide 5-meter seamless printing eliminates ugly panel seams",
      "Heavy black-back film prevents girder shadows from showing in sunlight",
      "Super-pigmented solvent inks retain saturation in high-exposure locations",
    ],
  },
  {
    id: "prod-standees",
    slug: "standees",
    name: "Roll-Up Retractable Standees",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Portable aluminum roll-up banner stands with non-tear high-resolution satin media.",
    description: "Set up professional presentations anywhere in 30 seconds. Includes heavy aluminum self-retracting cassette, interlocking support pole, and padded nylon shoulder carry case.",
    basePrice: 899,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 178,
    images: ["/images/cat-banners.jpg", "/images/prod-banner.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Standee", "Rollup Banner", "Exhibition", "Trade Show"],
    sizeOptions: [
      { id: "std-2x5", label: "2 x 5 Feet (Compact)", dimensions: "60 x 150 cm", multiplier: 0.9 },
      { id: "std-2.5x6", label: "2.5 x 6 Feet (Standard)", dimensions: "76 x 182 cm", multiplier: 1.0, default: true },
      { id: "std-3x6", label: "3 x 6 Feet (Wide Expo)", dimensions: "91 x 182 cm", multiplier: 1.25 },
    ],
    materialOptions: [
      { id: "eco-standee", label: "Silver Economy Aluminum Base", description: "Standard cassette with twist-out stabilizing feet", extraPricePerUnit: 0, default: true },
      { id: "luxury-base", label: "Heavy Luxury Teardrop Base", description: "Sleek chrome endcaps with wide stable footprint", extraPricePerUnit: 350 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 8 },
      { quantity: 5, discountPercent: 16 },
      { quantity: 10, discountPercent: 25 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
    },
    specifications: {
      "Graphic Media": "280 Micron Non-Tear Anti-Curl PP Satin Film",
      "Hardware": "100% Anodized Rust-Proof Aluminum",
      "Carry Bag": "Reinforced 600D Oxford Nylon Carry Bag with zipper",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "Zero-curl edges on graphic film guarantee upright presentation",
      "Quick retract spring mechanism tested for over 500 extensions",
      "Extremely portable for flights, cabs, and conference venues",
    ],
  },
  {
    id: "prod-glow-signs",
    slug: "glow-signs",
    name: "Backlit Glow Sign Boards",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Custom LED-illuminated commercial shopfront box signboards with translucent flex faces.",
    description: "Make your retail establishment visible 24/7. Built with sturdy galvanized iron frames, waterproof high-lumen LED modules, and vibrant translucent backlit flex skins.",
    basePrice: 1899,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 72,
    images: ["/images/cat-banners.jpg"],
    isFeatured: false,
    tags: ["Glow Sign", "Backlit", "Shopfront Board", "LED Sign"],
    sizeOptions: [
      { id: "glow-4x2", label: "4 x 2 Feet (8 sq ft)", dimensions: "120 x 60 x 15 cm", multiplier: 1.0, default: true },
      { id: "glow-6x3", label: "6 x 3 Feet (18 sq ft)", dimensions: "180 x 90 x 15 cm", multiplier: 2.1 },
      { id: "glow-8x3", label: "8 x 3 Feet (24 sq ft)", dimensions: "240 x 90 x 15 cm", multiplier: 2.8 },
      { id: "glow-10x4", label: "10 x 4 Feet (40 sq ft)", dimensions: "300 x 120 x 18 cm", multiplier: 4.5 },
    ],
    materialOptions: [
      { id: "tube-light", label: "Energy Efficient LED Tube System", description: "Uniform daylight white illumination", extraPricePerUnit: 0, default: true },
      { id: "samsung-led", label: "IP67 Waterproof Samsung LED Lens Modules", description: "High-output ultra bright with 3-yr driver", extraPricePerUnit: 500 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 6 },
      { quantity: 4, discountPercent: 12 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 50,
      hasFileUpload: true,
    },
    specifications: {
      "Frame Structure": "1-inch 18-Gauge Square Galvanized Iron (GI) Pipe",
      "Outer Cabinet": "Color-coated aluminum composite panel (ACP) or GI sheet",
      "Flex Face": "510 GSM Backlit Translucent Flex with double-pass print",
      "Power Supply": "Meanwell / Philips 12V IP67 Constant Voltage Driver",
      "Turnaround": "3 to 5 Business Days",
    },
    features: [
      "Double-pass density print ensures brilliant colors when illuminated at night",
      "Rainproof ventilation louvers prevent internal condensation",
      "Ready-to-mount heavy anchor brackets included",
    ],
  },
  {
    id: "prod-neon-boards",
    slug: "neon-boards",
    name: "Custom LED Neon Flex Signage",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Vibrant neon flex signage on laser-cut acrylic backings for cafes, lounges, and salons.",
    description: "The modern, shatterproof alternative to traditional glass neon. Crafted with flexible silicone LED tubing mounted on precision laser-cut acrylic. Low energy, cool to the touch, and dimmable.",
    basePrice: 2499,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.9,
    reviewCount: 94,
    images: ["/images/cat-banners.jpg", "/images/hero-composition.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Neon Sign", "LED Neon", "Cafe Decor", "Wall Light", "Aesthetic"],
    sizeOptions: [
      { id: "neon-2x1", label: "Small (Up to 24 x 12 in)", dimensions: "60 x 30 cm", multiplier: 1.0, default: true },
      { id: "neon-3x1.5", label: "Medium (Up to 36 x 18 in)", dimensions: "90 x 45 cm", multiplier: 1.6 },
      { id: "neon-4x2", label: "Large (Up to 48 x 24 in)", dimensions: "120 x 60 cm", multiplier: 2.3 },
    ],
    materialOptions: [
      { id: "clear-acrylic", label: "5mm Clear Acrylic Contour Cut", description: "Invisible transparent backing cut to shape", extraPricePerUnit: 0, default: true },
      { id: "black-acrylic", label: "5mm Gloss Black Acrylic Base", description: "Striking contrast for corporate logos", extraPricePerUnit: 250 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 10 },
      { quantity: 5, discountPercent: 18 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 25,
      hasFileUpload: true,
      uploadInstructions: "Upload logo vector or write custom lettering text.",
    },
    specifications: {
      "LED Strip": "6x12mm High-Brightness Food-Grade Silicone Neon Flex",
      "Power Adaptor": "12V 3A – 5A Bureau of Indian Standards (BIS) Certified",
      "Lifespan": "50,000+ Operating Hours",
      "Controls": "Free wireless remote dimmer & pulse controller included",
      "Turnaround": "3 to 4 Business Days",
    },
    features: [
      "Shatter-proof silicone tubing will never crack like fragile glass neon",
      "Remote controller with 10-step dimming and rhythmic party flashing modes",
      "Pre-drilled mounting holes with chrome standoff bolts included",
    ],
  },
  {
    id: "prod-3d-letter-board",
    slug: "3d-letter-board",
    name: "3D Acrylic & Metal Channel Letter Signs",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Architectural 3D channel letters with front or halo LED illumination on ACP backdrops.",
    description: "Transform your building facade into a landmark. Fabricated from laser-cut cast acrylic, stainless steel, and aluminum profile channel letters with embedded Samsung LEDs.",
    basePrice: 3299,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.9,
    reviewCount: 41,
    images: ["/images/cat-banners.jpg"],
    isFeatured: false,
    tags: ["3D Letters", "Channel Letters", "Storefront Sign", "Halo Glow"],
    sizeOptions: [
      { id: "letter-6in", label: "6 to 8 Inch Letter Height", dimensions: "Per letter depth 2-3 in", multiplier: 1.0, default: true },
      { id: "letter-12in", label: "10 to 12 Inch Letter Height", dimensions: "Per letter depth 3-4 in", multiplier: 1.8 },
      { id: "letter-18in", label: "15 to 18 Inch Letter Height", dimensions: "Per letter depth 4 in", multiplier: 2.7 },
    ],
    materialOptions: [
      { id: "acrylic-front", label: "Frontlit Cast Acrylic Letters", description: "Face glows bright white or colored LED", extraPricePerUnit: 0, default: true },
      { id: "ss-backlit", label: "Titanium Gold Stainless Steel (Halo Glow)", description: "Luxurious backlight glow on wall surface", extraPricePerUnit: 800 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 5 },
      { quantity: 5, discountPercent: 12 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 40,
      hasFileUpload: true,
    },
    specifications: {
      "Materials": "3mm Cast Acrylic Face + SS 304 Grade Return Edge",
      "Illumination": "Injection Molded Samsung LED Modules IP68",
      "Mounting Template": "1:1 Paper Installation Blueprint Stencil Included",
      "Turnaround": "5 to 7 Business Days",
    },
    features: [
      "Premium architectural styling for corporate headquarters and boutiques",
      "100% rustproof grade 304 stainless steel resists monsoon weathering",
      "Full 1:1 scale stencil included for effortless contractor installation",
    ],
  },
  {
    id: "prod-name-plates",
    slug: "name-plates",
    name: "Laser Engraved Corporate & House Nameplates",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Laser engraved brass, acrylic, and wood finish nameplates for clinic doors and residences.",
    description: "Welcome guests and clients with an exquisite personalized nameplate. Precision laser-etched letters filled with enamel colors on mirror-polished metal or frosted acrylic.",
    basePrice: 599,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 118,
    images: ["/images/cat-banners.jpg", "/images/cat-business-cards.jpg"],
    isFeatured: false,
    tags: ["Nameplate", "Door Sign", "Corporate Sign", "Brass Plate", "Doctor Clinic"],
    sizeOptions: [
      { id: "np-9x4", label: "Desk & Cabin (9 x 4 in)", dimensions: "23 x 10 cm", multiplier: 1.0, default: true },
      { id: "np-12x6", label: "Door Entrance (12 x 6 in)", dimensions: "30 x 15 cm", multiplier: 1.4 },
      { id: "np-16x8", label: "Bungalow Villa (16 x 8 in)", dimensions: "40 x 20 cm", multiplier: 1.9 },
    ],
    materialOptions: [
      { id: "np-acrylic", label: "Double-Layer Frosted Acrylic (6mm)", description: "Modern minimalist look with chrome studs", extraPricePerUnit: 0, default: true },
      { id: "np-brass", label: "Polished Gold Brass Sheet on Wooden Base", description: "Traditional executive prestige", extraPricePerUnit: 350 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 3, discountPercent: 10 },
      { quantity: 10, discountPercent: 20 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 40,
      hasFileUpload: true,
    },
    specifications: {
      "Laser Precision": "Fiber Laser Etching 0.05mm tolerance",
      "Weather Coating": "Clear Polyurethane UV seal prevents tarnish and oxidization",
      "Hardware": "Pair of solid brass chrome-plated standoff spacers & wall plugs",
      "Turnaround": "48 Hours",
    },
    features: [
      "Weather-sealed coating prevents outdoor metal tarnishing",
      "High-contrast color infill guarantees legible reading from distance",
      "Architectural standoff studs create an elegant floating shadow effect",
    ],
  },
  {
    id: "prod-acrylic-boards",
    slug: "acrylic-boards",
    name: "Clear Cast Acrylic Display Boards with Standoffs",
    categorySlug: "outdoor-advertising",
    categoryName: "Outdoor Advertising",
    shortDescription: "Ultra-clear glass-look acrylic signage panels with reverse UV printing and stainless hardware.",
    description: "The sleek, modern alternative to bulky signboards. Reverse-printed on the backside of 5mm cast acrylic to protect graphics against scratches, cleaning chemicals, and weather.",
    basePrice: 999,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 88,
    images: ["/images/cat-banners.jpg"],
    isFeatured: false,
    tags: ["Acrylic Sign", "Floating Sign", "Lobby Board", "Corporate Reception"],
    sizeOptions: [
      { id: "acr-18x12", label: "18 x 12 Inches (45 x 30 cm)", dimensions: "45 x 30 cm", multiplier: 1.0, default: true },
      { id: "acr-24x18", label: "24 x 18 Inches (60 x 45 cm)", dimensions: "60 x 45 cm", multiplier: 1.6 },
      { id: "acr-36x24", label: "36 x 24 Inches (90 x 60 cm)", dimensions: "90 x 60 cm", multiplier: 2.5 },
    ],
    materialOptions: [
      { id: "clear-5mm", label: "5mm Virgin Cast Clear Acrylic", description: "Glass-like clarity with diamond polished edges", extraPricePerUnit: 0, default: true },
      { id: "clear-8mm", label: "8mm Heavy Duty Cast Acrylic", description: "Substantial architectural depth", extraPricePerUnit: 400 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 8 },
      { quantity: 5, discountPercent: 18 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 50,
      hasFileUpload: true,
    },
    specifications: {
      "Material": "100% Virgin Cast PMMA Acrylic (No recycled scrap)",
      "Edges": "CNC Diamond Wheel Polished & Flame Buffed",
      "Print Process": "Reverse Direct-To-Substrate UV Flatbed with White Ink Backing",
      "Turnaround": "48 to 72 Hours",
    },
    features: [
      "Direct reverse printing seals your artwork safely behind clear acrylic",
      "Diamond flame-polished edges shimmer like real optical crystal",
      "Four stainless steel architectural standoff bolts included in kit",
    ],
  },
];
