import { CatalogProduct } from "../catalog";

export const PACKAGING_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-paper-bags",
    slug: "custom-paper-bags",
    name: "Custom Branded Kraft Paper Bags",
    categorySlug: "packaging",
    categoryName: "Packaging",
    shortDescription: "Eco-friendly retail shopping bags with twisted paper handles and reinforced bottom cards.",
    description: "Upgrade your retail store or boutique unboxing experience. Fabricated from 100% recyclable virgin virgin kraft paper or bleached white paper, fitted with strong twisted paper cord handles.",
    basePrice: 899,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.8,
    reviewCount: 164,
    images: ["/images/cat-gifts.jpg", "/images/cat-brochures.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Paper Bags", "Retail Packaging", "Eco-Friendly", "Kraft Bags"],
    sizeOptions: [
      { id: "bag-s", label: "Small Boutique (8 x 10 x 3.5 in)", dimensions: "20 x 25 x 9 cm", multiplier: 1.0, default: true },
      { id: "bag-m", label: "Medium Retail (10 x 14 x 4.5 in)", dimensions: "25 x 35 x 11 cm", multiplier: 1.35 },
      { id: "bag-l", label: "Large Apparel (14 x 16 x 5 in)", dimensions: "35 x 40 x 13 cm", multiplier: 1.7 },
    ],
    materialOptions: [
      { id: "kraft-brown", label: "150 GSM Natural Brown Kraft", description: "Eco-rustic aesthetic with durable fibers", extraPricePerUnit: 0, default: true },
      { id: "kraft-white", label: "170 GSM Bleached White Kraft", description: "Bright white for vivid multi-color graphics", extraPricePerUnit: 2.5 },
      { id: "art-coated", label: "210 GSM Art Board with Matte Lamination", description: "Luxury boutique finish with ribbon handle", extraPricePerUnit: 6.0 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 12 },
      { quantity: 500, discountPercent: 24 },
      { quantity: 1000, discountPercent: 36 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 40,
      hasFileUpload: true,
      uploadInstructions: "Vector artwork with front, back, and side gusset layouts.",
    },
    specifications: {
      "Load Capacity": "Holds up to 3 to 5 kg comfortably",
      "Handles": "Twisted paper cord, cotton rope, or satin ribbon options",
      "Reinforcement": "Thick card insert at base and folded turnover top rim",
      "Turnaround": "4 to 6 Business Days",
    },
    features: [
      "100% biodegradable and compliant with single-use plastic bans",
      "Reinforced top turn and cardboard base prevent handle tear-out",
      "Custom printing on front, back, and both side expandable gussets",
    ],
  },
  {
    id: "prod-packaging-boxes",
    slug: "packaging-boxes",
    name: "Corrugated E-Commerce & Product Shipping Boxes",
    categorySlug: "packaging",
    categoryName: "Packaging",
    shortDescription: "Custom printed 3-ply corrugated mailer boxes with secure self-locking tuck flaps.",
    description: "Protect fragile items and delight online shoppers during delivery. Precision die-cut corrugated mailers with crush-resistant walls and full exterior and interior edge-to-edge printing.",
    basePrice: 999,
    pricingModel: "batch",
    baseQuantity: 50,
    rating: 4.9,
    reviewCount: 110,
    images: ["/images/cat-gifts.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Shipping Boxes", "Mailer Box", "Packaging", "Corrugated", "E-Commerce"],
    sizeOptions: [
      { id: "box-s", label: "Small Mailer (6 x 4 x 2 in)", dimensions: "15 x 10 x 5 cm", multiplier: 1.0, default: true },
      { id: "box-m", label: "Medium Mailer (9 x 6 x 3 in)", dimensions: "23 x 15 x 8 cm", multiplier: 1.4 },
      { id: "box-l", label: "Large Mailer (12 x 9 x 4 in)", dimensions: "30 x 23 x 10 cm", multiplier: 1.9 },
    ],
    materialOptions: [
      { id: "ply-e", label: "E-Flute Corrugated (1.5mm Slim & Rigid)", description: "Sharp folding with clean die lines", extraPricePerUnit: 0, default: true },
      { id: "ply-b", label: "B-Flute Heavy Corrugated (3mm Cushioning)", description: "Maximum shock absorption for heavy goods", extraPricePerUnit: 5 },
    ],
    quantityTiers: [
      { quantity: 50, discountPercent: 0, default: true },
      { quantity: 100, discountPercent: 15 },
      { quantity: 250, discountPercent: 28 },
      { quantity: 500, discountPercent: 40 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "Download our 3D dieline template and map exterior + interior panels.",
    },
    specifications: {
      "Strength": "32 ECT (Edge Crush Test) / 150 GSM fluting",
      "Assembly": "Easy fold self-locking design (No tape required for box assembly)",
      "Print Finish": "High-density water-based ink with protective matte varnish",
      "Turnaround": "5 to 7 Business Days",
    },
    features: [
      "Interlocking dust flaps seal out courier dirt, rain, and debris",
      "Interior unboxing branding prints vivid brand colors inside the lid",
      "Flat-packed for minimal shipping and storage volume",
    ],
  },
  {
    id: "prod-packaging-labels",
    slug: "packaging-labels",
    name: "Tamper-Proof Fragile & Brand Packaging Labels",
    categorySlug: "packaging",
    categoryName: "Packaging",
    shortDescription: "Custom box sealing tape labels and tamper-evident void security sticker seals.",
    description: "Secure cartons against transit theft and instruct delivery couriers with clear handling marks. Printed with aggressive permanent adhesive that sticks firmly to porous corrugated cardboard.",
    basePrice: 349,
    pricingModel: "batch",
    baseQuantity: 250,
    rating: 4.7,
    reviewCount: 74,
    images: ["/images/cat-stickers.jpg"],
    isFeatured: false,
    tags: ["Packaging Labels", "Tamper Evident", "Box Seal", "Shipping Warning"],
    sizeOptions: [
      { id: "lbl-seal", label: "Box Top Seal (50 x 100 mm)", dimensions: "50 x 100 mm", multiplier: 1.0, default: true },
      { id: "lbl-round", label: "Circular Brand Wafer Seal (50 mm Dia)", dimensions: "50 mm diameter", multiplier: 0.85 },
      { id: "lbl-fragile", label: "Warning / Fragile Caution (75 x 125 mm)", dimensions: "75 x 125 mm", multiplier: 1.3 },
    ],
    materialOptions: [
      { id: "lbl-chroma", label: "80 GSM Gloss Chromo Paper Adhesive", description: "Standard cardboard permanent adhesive", extraPricePerUnit: 0, default: true },
      { id: "lbl-void", label: "Tamper-Evident VOID Security Film", description: "Leaves indelible 'VOID OPENED' residue when peeled", extraPricePerUnit: 0.8 },
    ],
    quantityTiers: [
      { quantity: 250, discountPercent: 0, default: true },
      { quantity: 500, discountPercent: 15 },
      { quantity: 1000, discountPercent: 28 },
      { quantity: 2500, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
    },
    specifications: {
      "Adhesive": "Hot-melt high-tack rubber adhesive for rough brown carton boxes",
      "Delivery Format": "Supplied on easy-peel rolls or split-back individual sheets",
      "Temperature Range": "-10°C to +60°C operational stability",
      "Turnaround": "48 Hours",
    },
    features: [
      "Aggressive adhesive bonds instantly with recycled paper cartons",
      "Prevents undetectable parcel tampering and theft during courier transit",
      "Clear iconography for 'Fragile - Handle With Care' and 'Do Not Drop'",
    ],
  },
  {
    id: "prod-hang-tags",
    slug: "hang-tags",
    name: "Garment & Apparel Swing Hang Tags with Eyelets",
    categorySlug: "packaging",
    categoryName: "Packaging",
    shortDescription: "Die-cut apparel price tags with drilled string eyelets and embossed brand logos.",
    description: "Elevate your clothing label, handmade crafts, and fashion accessories. Printed on rigid 400 GSM board with brass eyelet punching and optional cotton cord attachment.",
    basePrice: 449,
    pricingModel: "batch",
    baseQuantity: 250,
    rating: 4.8,
    reviewCount: 98,
    images: ["/images/cat-business-cards.jpg", "/images/cat-gifts.jpg"],
    isFeatured: false,
    tags: ["Hang Tags", "Clothing Tags", "Apparel", "Price Tags", "Garment"],
    sizeOptions: [
      { id: "tag-std", label: "Standard Rectangle (50 x 90 mm)", dimensions: "50 x 90 mm", multiplier: 1.0, default: true },
      { id: "tag-slim", label: "Slim Bookmark (40 x 120 mm)", dimensions: "40 x 120 mm", multiplier: 1.1 },
      { id: "tag-circle", label: "Round Tag (60 mm Diameter)", dimensions: "60 mm circle", multiplier: 1.25 },
    ],
    materialOptions: [
      { id: "card-400", label: "400 GSM Rigid Art Board (Matte Lamination)", description: "Sturdy card with velvet coat", extraPricePerUnit: 0, default: true },
      { id: "kraft-400", label: "400 GSM Raw Vintage Kraft Board", description: "Rustic denim and eco-wear look", extraPricePerUnit: 0.3 },
    ],
    quantityTiers: [
      { quantity: 250, discountPercent: 0, default: true },
      { quantity: 500, discountPercent: 15 },
      { quantity: 1000, discountPercent: 28 },
      { quantity: 2500, discountPercent: 44 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
    },
    specifications: {
      "Hole Punch": "3mm or 5mm round hole with optional metallic eyelet rim",
      "Printing": "Double-sided full color (Front logo + Back barcode & wash care details)",
      "Edges": "Straight cut or rounded corners",
      "Turnaround": "3 to 4 Business Days",
    },
    features: [
      "Rigid board will not bend or crease inside garment packaging",
      "Smooth writable back side for stamping size, MRP, and SKU barcode",
      "Optional natural jute or black nylon tag safety lock pins supplied",
    ],
  },
];
