import { CatalogProduct } from "../catalog";

export const PHOTO_CUSTOM_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-photo-prints",
    slug: "photo-prints",
    name: "Archival Luster & Gloss Photo Prints",
    categorySlug: "photo-custom-printing",
    categoryName: "Photo & Custom Printing",
    shortDescription: "True photographic lab prints on archival paper with vivid color gamuts and 100-year fade resistance.",
    description: "Preserve family vacations, wedding portraits, and wildlife photography with museum-grade digital photo printing. Printed on authentic Fuji Crystal Archive silver halide paper.",
    basePrice: 249,
    pricingModel: "batch",
    baseQuantity: 10,
    rating: 4.9,
    reviewCount: 160,
    images: ["/images/promo-banner.jpg", "/images/cat-gifts.jpg"],
    isFeatured: false,
    tags: ["Photo Prints", "Photography", "Archival", "Portraits", "Album"],
    sizeOptions: [
      { id: "ph-4x6", label: "4 x 6 Inches (10 x 15 cm)", dimensions: "10 x 15 cm", multiplier: 1.0, default: true },
      { id: "ph-5x7", label: "5 x 7 Inches (13 x 18 cm)", dimensions: "13 x 18 cm", multiplier: 1.4 },
      { id: "ph-8x12", label: "8 x 12 Inches / A4 (20 x 30 cm)", dimensions: "20 x 30 cm", multiplier: 2.2 },
      { id: "ph-12x18", label: "12 x 18 Inches / A3 (30 x 45 cm)", dimensions: "30 x 45 cm", multiplier: 3.5 },
    ],
    materialOptions: [
      { id: "paper-luster", label: "260 GSM Premium Luster / Pearl", description: "Fingerprint-resistant soft texture", extraPricePerUnit: 0, default: true },
      { id: "paper-gloss", label: "260 GSM High Gloss Photographic Paper", description: "Maximum contrast and razor sharpness", extraPricePerUnit: 0 },
      { id: "paper-metallic", label: "Metallic Pearl Fine Art Board", description: "Luminous chrome-like depth", extraPricePerUnit: 15 },
    ],
    quantityTiers: [
      { quantity: 10, discountPercent: 0, default: true },
      { quantity: 25, discountPercent: 12 },
      { quantity: 50, discountPercent: 24 },
      { quantity: 100, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "High-resolution JPEG/TIFF with sRGB or AdobeRGB color profile.",
    },
    specifications: {
      "Print Process": "Noritsu 12-Color Professional Photo Laser Engine",
      "Longevity": "100+ Years archival rating under normal indoor display",
      "Surface Finish": "Micro-porous coating prevents fingerprint smudges",
      "Turnaround": "24 Hours",
    },
    features: [
      "Continuous tone laser printing delivers lifelike skin tones and smooth gradients",
      "True black reproduction with ultra-deep dynamic density (D-Max)",
      "Thick photographic substrate will not warp or curl",
    ],
  },
  {
    id: "prod-canvas-prints",
    slug: "canvas-prints",
    name: "Gallery-Wrapped Stretched Canvas Prints",
    categorySlug: "photo-custom-printing",
    categoryName: "Photo & Custom Printing",
    shortDescription: "Textured cotton canvas stretched over seasoned pine wood frames, ready to hang.",
    description: "Transform your favorite memories into fine art gallery centerpieces. Hand-stretched over kiln-dried pinewood stretcher bars with folded corners and brass hanging hardware attached.",
    basePrice: 699,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.9,
    reviewCount: 145,
    images: ["/images/promo-banner.jpg", "/images/hero-composition.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Canvas", "Wall Decor", "Fine Art", "Home Decor", "Gallery Wrap"],
    sizeOptions: [
      { id: "can-12x12", label: "12 x 12 Inches (Square)", dimensions: "30 x 30 cm", multiplier: 1.0, default: true },
      { id: "can-18x12", label: "18 x 12 Inches (Standard)", dimensions: "45 x 30 cm", multiplier: 1.35 },
      { id: "can-24x16", label: "24 x 16 Inches (Grand)", dimensions: "60 x 40 cm", multiplier: 1.8 },
      { id: "can-36x24", label: "36 x 24 Inches (Statement)", dimensions: "90 x 60 cm", multiplier: 2.8 },
    ],
    materialOptions: [
      { id: "can-cotton-380", label: "380 GSM 100% Pure Cotton Canvas", description: "Authentic painterly texture with satin UV varnish", extraPricePerUnit: 0, default: true },
      { id: "can-poly-waterproof", label: "300 GSM Poly-Cotton Waterproof Canvas", description: "Ultra-vivid colors and wipe-clean surface", extraPricePerUnit: -50 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 8 },
      { quantity: 4, discountPercent: 18 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
      uploadInstructions: "Allow 1.5 inch bleed area around artwork for wrapped edges.",
    },
    specifications: {
      "Stretcher Frame": "0.75 or 1.25 Inch Solid Kiln-Dried Pinewood Bars (Warp-free)",
      "Edge Style": "Mirrored Image Wrap or Solid Color Edge",
      "Varnish": "Water-based satin UV protective coating prevents cracking and fading",
      "Hardware": "Pre-installed sawtooth hanger + drywall screws included",
      "Turnaround": "48 Hours",
    },
    features: [
      "Hand-stretched by skilled craftsmen for drum-tight tension",
      "Satin protective coating makes canvas easy to dust with a damp cloth",
      "Arrives completely assembled and 100% ready to hang on your wall",
    ],
  },
  {
    id: "prod-photo-frames",
    slug: "photo-frames",
    name: "Contemporary Black & Wooden Photo Frames",
    categorySlug: "photo-custom-printing",
    categoryName: "Photo & Custom Printing",
    shortDescription: "Minimalist fiberwood photo frames with shatterproof acrylic glass and custom matting.",
    description: "Display family portraits, diplomas, and memories in gallery-style frames. Includes acid-free beveled mat borders, high-clarity acrylic safety face, and dual-direction wall hanging brackets.",
    basePrice: 499,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 96,
    images: ["/images/cat-gifts.jpg"],
    isFeatured: false,
    tags: ["Photo Frames", "Wall Art", "Framed Prints", "Gift"],
    sizeOptions: [
      { id: "frm-8x10", label: "8 x 10 Inches (Holds 5x7 photo with mount)", dimensions: "20 x 25 cm", multiplier: 1.0, default: true },
      { id: "frm-12x16", label: "12 x 16 Inches (Holds 8x12 photo with mount)", dimensions: "30 x 40 cm", multiplier: 1.45 },
      { id: "frm-16x20", label: "16 x 20 Inches (Holds 12x16 photo with mount)", dimensions: "40 x 50 cm", multiplier: 2.1 },
    ],
    materialOptions: [
      { id: "frm-matte-black", label: "Sleek Matte Black Synthetic Wood", description: "Modern minimalist gallery style", extraPricePerUnit: 0, default: true },
      { id: "frm-warm-teak", label: "Warm Natural Teak Finish Wood", description: "Rustic organic warmth", extraPricePerUnit: 80 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 2, discountPercent: 8 },
      { quantity: 5, discountPercent: 18 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
      uploadInstructions: "Upload photo to receive fully printed and mounted frame.",
    },
    specifications: {
      "Frame Profile": "0.75-inch flat profile engineered fiberwood",
      "Glazing": "1.5mm Shatter-Resistant Optical Cast Acrylic (Safer than heavy fragile glass)",
      "Mat Board": "1.4mm Acid-Free Bevel Cut White Core Passe-Partout",
      "Turnaround": "48 Hours",
    },
    features: [
      "Includes professional photo print already mounted inside frame",
      "Shatterproof acrylic ensures safe shipping without transit glass breakage",
      "Versatile backing allows both portrait and landscape wall mounting",
    ],
  },
  {
    id: "prod-t-shirt-printing",
    slug: "t-shirt-printing",
    name: "Custom Branded Cotton T-Shirts",
    categorySlug: "photo-custom-printing",
    categoryName: "Photo & Custom Printing",
    shortDescription: "100% combed cotton biowashed tees with DTF direct-to-film high-definition printing.",
    description: "Outfit your company team, event volunteers, or college fest with custom printed crewneck t-shirts. Soft-hand feel, pre-shrunk cotton fabric with flexible prints that won't crack or peel.",
    basePrice: 399,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 184,
    images: ["/images/promo-banner.jpg", "/images/hero-composition.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["T-Shirts", "Apparel", "Custom Clothing", "DTF Printing", "Corporate Merch"],
    sizeOptions: [
      { id: "ts-s", label: "S (Chest 38 in)", dimensions: "Chest 38 in / Length 26 in", multiplier: 1.0 },
      { id: "ts-m", label: "M (Chest 40 in)", dimensions: "Chest 40 in / Length 27 in", multiplier: 1.0, default: true },
      { id: "ts-l", label: "L (Chest 42 in)", dimensions: "Chest 42 in / Length 28 in", multiplier: 1.0 },
      { id: "ts-xl", label: "XL (Chest 44 in)", dimensions: "Chest 44 in / Length 29 in", multiplier: 1.0 },
      { id: "ts-xxl", label: "2XL (Chest 46 in)", dimensions: "Chest 46 in / Length 30 in", multiplier: 1.1 },
    ],
    materialOptions: [
      { id: "tee-bio-180", label: "180 GSM 100% Combed Biowashed Cotton", description: "Breathable everyday comfort fit", extraPricePerUnit: 0, default: true },
      { id: "tee-heavy-240", label: "240 GSM Heavyweight Oversized French Terry", description: "Trendy streetwear silhouette", extraPricePerUnit: 120 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 10, discountPercent: 15 },
      { quantity: 25, discountPercent: 28 },
      { quantity: 100, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
      uploadInstructions: "Upload transparent PNG at 300 DPI. Specify chest or back placement.",
    },
    specifications: {
      "Fabric Composition": "100% Ring-Spun Super-Combed Cotton (Biowashed & Pre-Shrunk)",
      "Print Technology": "Japanese Direct-To-Film (DTF) Industrial Pigment Transfer",
      "Wash Care": "Machine wash cold inside-out, tumble dry low, do not iron directly on print",
      "Turnaround": "48 Hours",
    },
    features: [
      "Ultra-soft biowash finish removes surface fuzz and prevents pill balling",
      "Stretches naturally with fabric without cracking or flaking off",
      "Ribbed lycra collar retains shape after dozens of machine washes",
    ],
  },
  {
    id: "prod-mug-printing",
    slug: "mug-printing",
    name: "Ceramic Sublimation Coffee Mugs",
    categorySlug: "photo-custom-printing",
    categoryName: "Photo & Custom Printing",
    shortDescription: "Glossy white 330ml ceramic mugs with permanent full-color panoramic photo wrapping.",
    description: "Start every morning with your favorite photos, witty quotes, or corporate logo. High-grade AAA ceramic coated with polymer glaze for 100% dishwasher and microwave safe longevity.",
    basePrice: 199,
    pricingModel: "unit",
    baseQuantity: 1,
    rating: 4.8,
    reviewCount: 220,
    images: ["/images/cat-gifts.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Mugs", "Coffee Mug", "Custom Mug", "Gifts", "Sublimation"],
    sizeOptions: [
      { id: "mug-11oz", label: "Standard 11 oz (330 ml)", dimensions: "95 mm height x 82 mm diameter", multiplier: 1.0, default: true },
      { id: "mug-15oz", label: "Jumbo 15 oz (450 ml)", dimensions: "120 mm height x 85 mm diameter", multiplier: 1.35 },
    ],
    materialOptions: [
      { id: "mug-white", label: "Classic Glossy White Ceramic", description: "Crisp white background for any design", extraPricePerUnit: 0, default: true },
      { id: "mug-magic", label: "Color Changing Magic Mug (Black to Photo)", description: "Reveals secret photo when hot liquid is poured", extraPricePerUnit: 100 },
      { id: "mug-inner-color", label: "Dual-Tone (Colored Handle & Interior)", description: "Pop of accent color inside", extraPricePerUnit: 40 },
    ],
    quantityTiers: [
      { quantity: 1, discountPercent: 0, default: true },
      { quantity: 6, discountPercent: 12 },
      { quantity: 24, discountPercent: 25 },
      { quantity: 72, discountPercent: 40 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 40,
      hasFileUpload: true,
      uploadInstructions: "2000 x 900 px panoramic image wrap.",
    },
    specifications: {
      "Ceramic Grade": "AAA Quality High-Gloss Super White Ceramic",
      "Safety": "100% Non-Toxic, Lead-Free, Microwave & Dishwasher Safe",
      "Packaging": "Individual thermocol safety shell box inside cardboard gift carton",
      "Turnaround": "24 Hours",
    },
    features: [
      "Sublimation dye molecules fuse permanently into the glaze (Never peels)",
      "Comfortable C-shaped ergonomic handle with balanced weight distribution",
      "Drop-tested thermocol packaging guarantees zero transit breakage",
    ],
  },
  {
    id: "prod-keychain-printing",
    slug: "keychain-printing",
    name: "Custom Acrylic & Metal Photo Keychains",
    categorySlug: "photo-custom-printing",
    categoryName: "Photo & Custom Printing",
    shortDescription: "Durable laser-cut clear acrylic and engraved metal keychains with heavy split rings.",
    description: "Keep loved ones close or hand out memorable branded merchandise. Made with crystal clear cast acrylic or laser-engraved brushed stainless steel, paired with heavy-duty nickel keyrings.",
    basePrice: 299,
    pricingModel: "batch",
    baseQuantity: 10,
    rating: 4.7,
    reviewCount: 88,
    images: ["/images/cat-gifts.jpg", "/images/prod-stickers.jpg"],
    isFeatured: false,
    tags: ["Keychain", "Keyring", "Acrylic Keychain", "Merchandise", "Gifts"],
    sizeOptions: [
      { id: "kc-rec", label: "Rectangle (50 x 35 mm)", dimensions: "50 x 35 mm", multiplier: 1.0, default: true },
      { id: "kc-round", label: "Round Charm (45 mm Dia)", dimensions: "45 mm circle", multiplier: 1.0 },
      { id: "kc-custom", label: "Custom Contour Shape", dimensions: "Max 60 x 60 mm", multiplier: 1.25 },
    ],
    materialOptions: [
      { id: "kc-acrylic-clear", label: "3mm Clear Acrylic (Double-Sided Print)", description: "Sandwiched print won't scratch off", extraPricePerUnit: 0, default: true },
      { id: "kc-metal-engraved", label: "Brushed Gunmetal Stainless Steel", description: "Deep laser etched corporate finish", extraPricePerUnit: 15 },
    ],
    quantityTiers: [
      { quantity: 10, discountPercent: 0, default: true },
      { quantity: 25, discountPercent: 15 },
      { quantity: 50, discountPercent: 28 },
      { quantity: 100, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 25,
      hasFileUpload: true,
    },
    specifications: {
      "Hardware": "Heavy-duty 25mm nickel-plated tempered steel split ring & 4-link chain",
      "Protection": "Artwork sandwiched between two layers of acrylic for lifelong durability",
      "Turnaround": "48 Hours",
    },
    features: [
      "Artwork is fully sealed between acrylic layers and can never be scratched off",
      "Tempered steel key ring will not warp or loosen under heavy keys",
      "Double-sided printing allows photo on one side and custom message on back",
    ],
  },
];
