import { CatalogProduct } from "../catalog";

export const STATIONERY_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-notebooks",
    slug: "notebooks",
    name: "Custom Hardcover Corporate Notebooks",
    categorySlug: "stationery",
    categoryName: "Stationery",
    shortDescription: "Custom embossed hardcover notebooks with ribbon bookmark and 80 GSM natural shade paper.",
    description: "Equip your team and welcome new hires with custom branded casebound notebooks. Features durable hardcovers, debossed or UV-printed company logos, pen loop, and elastic closure bands.",
    basePrice: 749,
    pricingModel: "batch",
    baseQuantity: 25,
    rating: 4.9,
    reviewCount: 112,
    images: ["/images/cat-brochures.jpg", "/images/cat-business-cards.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Notebooks", "Hardcover", "Stationery", "Corporate Gifting"],
    sizeOptions: [
      { id: "nb-a5", label: "A5 Hardcover (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 1.0, default: true },
      { id: "nb-b5", label: "B5 Executive (176 x 250 mm)", dimensions: "176 x 250 mm", multiplier: 1.25 },
    ],
    materialOptions: [
      { id: "nb-ruled", label: "80 GSM Ruled Cream Paper (192 Pages)", description: "Feather-proof fountain-pen friendly", extraPricePerUnit: 0, default: true },
      { id: "nb-dotgrid", label: "100 GSM Dot Grid Designer Pages (192 Pages)", description: "Ideal for wireframing and bullet journaling", extraPricePerUnit: 15 },
    ],
    quantityTiers: [
      { quantity: 25, discountPercent: 0, default: true },
      { quantity: 50, discountPercent: 12 },
      { quantity: 100, discountPercent: 25 },
      { quantity: 250, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 30,
      hasFileUpload: true,
      uploadInstructions: "Vector EPS or PDF for blind deboss or foil stamping.",
    },
    specifications: {
      "Cover": "Hardboard wrapped in imported Italian PU Leatherette",
      "Page Count": "192 Pages (96 Sheets) thread-sewn section bound",
      "Features": "Satin ribbon bookmark + Expandable rear document pocket",
      "Turnaround": "5 to 7 Business Days",
    },
    features: [
      "Thread-sewn binding opens 180° completely flat for effortless writing",
      "Natural shade eye-protective paper eliminates harsh glare",
      "Premium debossed or gold foil stamped corporate logo branding",
    ],
  },
  {
    id: "prod-diaries",
    slug: "diaries",
    name: "Executive Leatherette Dated Diaries",
    categorySlug: "stationery",
    categoryName: "Stationery",
    shortDescription: "Annual dated corporate planners with day-to-page layouts and metallic edge gilding.",
    description: "The timeless corporate year-end gift. Features full-year dated calendar pages, international time zones, conversion charts, monthly goals, and luxury leatherette binding.",
    basePrice: 899,
    pricingModel: "batch",
    baseQuantity: 20,
    rating: 4.8,
    reviewCount: 96,
    images: ["/images/cat-brochures.jpg"],
    isFeatured: false,
    tags: ["Diaries", "Year Planner", "Corporate Gift", "Leatherette"],
    sizeOptions: [
      { id: "diary-reg", label: "Executive Regular (18 x 24 cm)", dimensions: "18 x 24 cm", multiplier: 1.0, default: true },
      { id: "diary-compact", label: "Pocket Executive (10 x 18 cm)", dimensions: "10 x 18 cm", multiplier: 0.8 },
    ],
    materialOptions: [
      { id: "diary-tan", label: "Rich Tan Thermo-PU Leatherette", description: "Color changes darker when hot-stamped", extraPricePerUnit: 0, default: true },
      { id: "diary-black", label: "Classic Matte Onyx Black", description: "Formal corporate look", extraPricePerUnit: 0 },
    ],
    quantityTiers: [
      { quantity: 20, discountPercent: 0, default: true },
      { quantity: 50, discountPercent: 15 },
      { quantity: 100, discountPercent: 28 },
      { quantity: 250, discountPercent: 40 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 25,
      hasFileUpload: true,
    },
    specifications: {
      "Format": "Day-a-Page Dated + Monthly Planner + Expense Trackers",
      "Paper": "70 GSM Super-Smooth Ivory Tint Paper",
      "Accents": "Magnetic clasp closure with metal monogram plate",
      "Turnaround": "5 to 7 Business Days",
    },
    features: [
      "Custom multi-page color corporate insert pages bound inside",
      "Thermal reactive leatherette allows deep, rich debossing of company logos",
      "Magnetic flap closure keeps contents organized and protected",
    ],
  },
  {
    id: "prod-notepads",
    slug: "notepads",
    name: "Custom Desk Scribble Notepads",
    categorySlug: "stationery",
    categoryName: "Stationery",
    shortDescription: "Padded memo note blocks with easy-tear gumming and custom header branding.",
    description: "Keep your brand on every executive desk and conference room table. Printed on absorbent 80 GSM bond paper with sturdy cardboard backing and micro-gummed top edges.",
    basePrice: 399,
    pricingModel: "batch",
    baseQuantity: 25,
    rating: 4.7,
    reviewCount: 78,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: false,
    tags: ["Notepad", "Desk Pad", "Memo", "Stationery", "Office"],
    sizeOptions: [
      { id: "pad-a5", label: "A5 Desk Size (148 x 210 mm)", dimensions: "148 x 210 mm", multiplier: 1.0, default: true },
      { id: "pad-a4", label: "A4 Conference Size (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.5 },
      { id: "pad-pocket", label: "Pocket Memo (90 x 140 mm)", dimensions: "90 x 140 mm", multiplier: 0.7 },
    ],
    materialOptions: [
      { id: "pad-50p", label: "50 Leaves Pad (80 GSM Executive Bond)", description: "Standard thickness", extraPricePerUnit: 0, default: true },
      { id: "pad-100p", label: "100 Leaves Pad (80 GSM Executive Bond)", description: "Heavy desk block", extraPricePerUnit: 8 },
    ],
    quantityTiers: [
      { quantity: 25, discountPercent: 0, default: true },
      { quantity: 50, discountPercent: 12 },
      { quantity: 100, discountPercent: 24 },
      { quantity: 250, discountPercent: 36 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 40,
      hasFileUpload: true,
    },
    specifications: {
      "Paper Stock": "80 GSM High-Brightness Bond Paper",
      "Binding": "Cold-melt flexible edge glue with chipboard back",
      "Pages per pad": "50 or 100 clean tear-away leaves",
      "Turnaround": "48 to 72 Hours",
    },
    features: [
      "Pages peel off cleanly without tearing or leaving sticky residue",
      "Stiff 600 GSM strawboard back provides solid support while writing without a desk",
      "Optional light watermark logo printed across writing lines",
    ],
  },
  {
    id: "prod-files-folders",
    slug: "files-folders",
    name: "Laminated Corporate Presentation Folders",
    categorySlug: "stationery",
    categoryName: "Stationery",
    shortDescription: "Die-cut document presentation folders with business card slits and interior pockets.",
    description: "Deliver proposals, legal agreements, and sales pitch collateral inside high-grade die-cut presentation folders. Printed on 350 GSM art card with internal expandable capacity pockets.",
    basePrice: 699,
    pricingModel: "batch",
    baseQuantity: 50,
    rating: 4.8,
    reviewCount: 65,
    images: ["/images/cat-brochures.jpg"],
    isFeatured: false,
    tags: ["Folders", "Presentation", "Corporate Documents", "Die-Cut Pocket"],
    sizeOptions: [
      { id: "folder-a4", label: "Holds A4 Documents (220 x 310 mm folded)", dimensions: "220 x 310 mm", multiplier: 1.0, default: true },
      { id: "folder-legal", label: "Holds Legal / FS Sheets (230 x 360 mm)", dimensions: "230 x 360 mm", multiplier: 1.3 },
    ],
    materialOptions: [
      { id: "matte-350-f", label: "350 GSM Art Board with Velvet Matte Lamination", description: "Non-reflective luxury touch", extraPricePerUnit: 0, default: true },
      { id: "gloss-350-f", label: "350 GSM Art Board with High Gloss Film", description: "Vibrant high-contrast sheen", extraPricePerUnit: 0 },
    ],
    quantityTiers: [
      { quantity: 50, discountPercent: 0, default: true },
      { quantity: 100, discountPercent: 15 },
      { quantity: 250, discountPercent: 28 },
      { quantity: 500, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: false,
      hasFileUpload: true,
      uploadInstructions: "Use our die-cut template to ensure graphics avoid pocket folds.",
    },
    specifications: {
      "Card Weight": "350 GSM Imported Food-Grade Art Board",
      "Pockets": "Right-hand or Dual Internal Pockets with card die-cuts",
      "Capacity": "Holds up to 25 to 30 sheets of A4 paper",
      "Turnaround": "3 to 4 Business Days",
    },
    features: [
      "Built-in die-cut slots neatly hold visiting cards inside pocket",
      "Creased 5mm spine allows generous document capacity without bulging",
      "Full exterior and interior color printing available",
    ],
  },
  {
    id: "prod-certificates",
    slug: "certificates",
    name: "Gold Foil Appreciation Certificates",
    categorySlug: "stationery",
    categoryName: "Stationery",
    shortDescription: "Laser-compatible certificates with hot-stamped gold foil borders and security watermarks.",
    description: "Honor academic excellence, training completions, and corporate milestones with ornate gold-foiled certificates printed on premium textured alabaster card.",
    basePrice: 549,
    pricingModel: "batch",
    baseQuantity: 50,
    rating: 4.9,
    reviewCount: 88,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: false,
    tags: ["Certificates", "Gold Foil", "Awards", "Graduation", "Diploma"],
    sizeOptions: [
      { id: "cert-a4", label: "A4 Standard (210 x 297 mm)", dimensions: "210 x 297 mm", multiplier: 1.0, default: true },
      { id: "cert-us", label: "US Letter (8.5 x 11 in)", dimensions: "216 x 279 mm", multiplier: 1.0 },
    ],
    materialOptions: [
      { id: "parchment-250", label: "250 GSM Classic Ivory Parchment", description: "Vintage academic aesthetic", extraPricePerUnit: 0, default: true },
      { id: "linen-300", label: "300 GSM Textured Royal Linen Board", description: "Subtle woven texture with gold foil trim", extraPricePerUnit: 4 },
    ],
    quantityTiers: [
      { quantity: 50, discountPercent: 0, default: true },
      { quantity: 100, discountPercent: 12 },
      { quantity: 250, discountPercent: 25 },
      { quantity: 500, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 1,
      freeCharLimit: 50,
      hasFileUpload: true,
    },
    specifications: {
      "Foil Stamping": "Mirror Metallic Gold or Silver Foil Border",
      "Laser Compatibility": "Safe for running through desktop laser printers to print recipient names",
      "Paper Stock": "250 – 300 GSM Acid-Free Archival Paper",
      "Turnaround": "48 Hours",
    },
    features: [
      "Pre-foiled borders ready for overprinting recipient names on your office printer",
      "Acid-free paper prevents yellowing or discoloration for decades",
      "Optional embossed foil security seals available",
    ],
  },
  {
    id: "prod-id-cards",
    slug: "id-cards",
    name: "Thermal PVC Identity Cards with Lanyards",
    categorySlug: "stationery",
    categoryName: "Stationery",
    shortDescription: "Waterproof solid PVC employee & student cards with satin lanyard ribbons and badge holders.",
    description: "Durable, credit-card thick PVC identity badges. Printed with high-definition dye-sublimation thermal transfer technology for crisp photos and readable barcodes.",
    basePrice: 450,
    pricingModel: "batch",
    baseQuantity: 10,
    rating: 4.8,
    reviewCount: 140,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["ID Cards", "PVC Badges", "Lanyards", "Corporate ID", "Student Cards"],
    sizeOptions: [
      { id: "id-cr80", label: "CR80 Standard (85.6 x 54 mm)", dimensions: "85.6 x 54 mm (0.76mm / 30 mil thick)", multiplier: 1.0, default: true },
    ],
    materialOptions: [
      { id: "id-card-only", label: "PVC Card Only", description: "Slot punched or plain", extraPricePerUnit: 0, default: true },
      { id: "id-with-lanyard", label: "PVC Card + 16mm Custom Printed Lanyard & Holder", description: "Complete ready-to-wear set", extraPricePerUnit: 25 },
    ],
    quantityTiers: [
      { quantity: 10, discountPercent: 0, default: true },
      { quantity: 25, discountPercent: 12 },
      { quantity: 50, discountPercent: 22 },
      { quantity: 100, discountPercent: 35 },
      { quantity: 500, discountPercent: 50 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 30,
      hasFileUpload: true,
      uploadInstructions: "Upload Excel data sheet along with high-res employee passport photos.",
    },
    specifications: {
      "Card Substrate": "100% Solid PVC Core with Overlay Lamination",
      "Thickness": "30 Mil / 760 Micron (ISO standard credit card gauge)",
      "Print Tech": "Double-Sided Edge-to-Edge Thermal Dye Sublimation",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "100% waterproof and scratch-proof overlay protection",
      "Seamless variable data printing (VDP) for names, photos, and barcodes",
      "Includes premium metal dog hook clips with custom satin lanyards",
    ],
  },
];
