import { CatalogProduct } from "../catalog";

export const WEDDING_EVENTS_PRODUCTS: CatalogProduct[] = [
  {
    id: "prod-wedding-cards",
    slug: "wedding-cards",
    name: "Royal Gold Foil Wedding Invitations",
    categorySlug: "wedding-events",
    categoryName: "Wedding & Events",
    shortDescription: "Luxury multi-insert wedding suites with hot metallic foil stamping and matching envelopes.",
    description: "Celebrate sacred unions with bespoke wedding invitation cards. Crafted on heavy textured handmade or metallic boards, embellished with precision hot-foil stamping, intricate laser lace cuts, and coordinated RSVP envelopes.",
    basePrice: 1999,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.9,
    reviewCount: 210,
    images: ["/images/cat-stickers.jpg", "/images/cat-business-cards.jpg"],
    isFeatured: true,
    isBestSeller: true,
    tags: ["Wedding Cards", "Shaadi Cards", "Gold Foil", "Luxury Invitations", "RSVP"],
    sizeOptions: [
      { id: "wed-std", label: "Royal Suite (180 x 240 mm)", dimensions: "180 x 240 mm", multiplier: 1.0, default: true },
      { id: "wed-grand", label: "Grand Boxed Suite (200 x 280 mm)", dimensions: "200 x 280 mm", multiplier: 1.4 },
    ],
    materialOptions: [
      { id: "board-metal", label: "350 GSM Metallic Shimmer Board with Gold Foil", description: "Sparkling jewel tone finish", extraPricePerUnit: 0, default: true },
      { id: "board-handmade", label: "400 GSM Deckled-Edge Cotton Handmade Paper", description: "Rustic vintage elegance", extraPricePerUnit: 12 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 200, discountPercent: 12 },
      { quantity: 300, discountPercent: 20 },
      { quantity: 500, discountPercent: 32 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 100,
      hasFileUpload: true,
      uploadInstructions: "Send couple names, wedding functions, date/venue text, and family elders' blessings.",
    },
    specifications: {
      "Suite Includes": "Main Outer Pocket Envelope + 2 to 3 Ceremony Inserts (Mehendi / Sangeet / Reception)",
      "Embellishments": "Genuine Hot-Stamp Gold/Rose-Gold Foil + Embossed Monogram Crest",
      "Envelope Seal": "Matching Self-Adhesive Peel-and-Seal or Wax Seal compatible flap",
      "Turnaround": "5 to 7 Business Days",
    },
    features: [
      "Custom couple initials monogram die-cut or foil stamped on front flap",
      "Includes separate insert cards for all multi-day ceremony functions",
      "Supplied with coordinated addressing envelopes ready for dispatch",
    ],
  },
  {
    id: "prod-invitation-cards",
    slug: "invitation-cards",
    name: "Premium Event & Birthday Invitations",
    categorySlug: "wedding-events",
    categoryName: "Wedding & Events",
    shortDescription: "Custom party, anniversary, and corporate gala invitation cards with matching envelopes.",
    description: "Set the mood for milestone birthdays, baby showers, housewarmings, and anniversary galas. Printed on heavy 350 GSM art stock with tactile matte velvet coating.",
    basePrice: 699,
    pricingModel: "batch",
    baseQuantity: 50,
    rating: 4.8,
    reviewCount: 92,
    images: ["/images/cat-stickers.jpg"],
    isFeatured: false,
    tags: ["Invitations", "Birthday", "Anniversary", "Party Cards", "Gala"],
    sizeOptions: [
      { id: "inv-5x7", label: "Classic 5 x 7 Inches (127 x 178 mm)", dimensions: "127 x 178 mm", multiplier: 1.0, default: true },
      { id: "inv-square", label: "Modern Square (150 x 150 mm)", dimensions: "150 x 150 mm", multiplier: 1.1 },
    ],
    materialOptions: [
      { id: "inv-velvet", label: "350 GSM Soft-Touch Velvet Matte", description: "Ultra-smooth suede touch", extraPricePerUnit: 0, default: true },
      { id: "inv-pearl", label: "300 GSM Pearlescent Shimmer Card", description: "Soft subtle metallic gleam", extraPricePerUnit: 3 },
    ],
    quantityTiers: [
      { quantity: 50, discountPercent: 0, default: true },
      { quantity: 100, discountPercent: 15 },
      { quantity: 200, discountPercent: 28 },
      { quantity: 500, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 60,
      hasFileUpload: true,
    },
    specifications: {
      "Cardstock": "300 – 350 GSM Heavy Rigid Board",
      "Envelope": "Includes premium 120 GSM color-matched Euro-flap envelopes",
      "Print Quality": "Indigo HD Digital Offset 2400 DPI",
      "Turnaround": "48 Hours",
    },
    features: [
      "Customized guest RSVP phone number and Google Maps QR code on back",
      "Vibrant full-bleed photography and celebratory graphics",
      "Includes premium gummed mailing envelopes for every invitation",
    ],
  },
  {
    id: "prod-thank-you-cards",
    slug: "thank-you-cards",
    name: "Custom Handwritten Style Thank You Cards",
    categorySlug: "wedding-events",
    categoryName: "Wedding & Events",
    shortDescription: "Folded and flat note cards with premium tactile surfaces designed for personal handwriting.",
    description: "Show genuine gratitude to wedding attendees, event donors, and retail patrons. Formulated on non-smear absorbent textured stock that accepts fountain pen, ballpoint, and gel inks flawlessly.",
    basePrice: 399,
    pricingModel: "batch",
    baseQuantity: 50,
    rating: 4.7,
    reviewCount: 64,
    images: ["/images/cat-business-cards.jpg"],
    isFeatured: false,
    tags: ["Thank You Cards", "Gratitude", "Note Cards", "Folded Cards"],
    sizeOptions: [
      { id: "ty-a6", label: "A6 Folded (105 x 148 mm folded)", dimensions: "Open 210 x 148 mm", multiplier: 1.0, default: true },
      { id: "ty-flat", label: "A6 Flat Postcard (105 x 148 mm)", dimensions: "105 x 148 mm", multiplier: 0.8 },
    ],
    materialOptions: [
      { id: "ty-matte", label: "300 GSM Natural Uncoated White Card", description: "Zero ink smudging when writing", extraPricePerUnit: 0, default: true },
      { id: "ty-textured", label: "300 GSM German Felt-Marked Textured Board", description: "Subtle woven fiber grain", extraPricePerUnit: 2 },
    ],
    quantityTiers: [
      { quantity: 50, discountPercent: 0, default: true },
      { quantity: 100, discountPercent: 12 },
      { quantity: 200, discountPercent: 24 },
      { quantity: 500, discountPercent: 38 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 40,
      hasFileUpload: true,
    },
    specifications: {
      "Ink Absorption": "Non-coated interior leaves ink dry in seconds without blotting",
      "Envelopes": "Includes pack of 50 pastel or white envelopes",
      "Scoring": "Machine pre-scored for sharp, clean center folds",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "Custom branded logo on back and decorative message on front cover",
      "Blank inside leaves generous space for heartfelt handwritten notes",
      "Fountain-pen safe paper eliminates bleeding and feathering",
    ],
  },
  {
    id: "prod-event-tickets",
    slug: "event-tickets",
    name: "Perforated Numbered Event Tickets with QR Code",
    categorySlug: "wedding-events",
    categoryName: "Wedding & Events",
    shortDescription: "Security tickets with sequential numbering, tear-off counterfoil stubs, and scannable QR codes.",
    description: "Control venue entry for concerts, charity galas, sporting matches, and club nights. Engineered with anti-counterfeit micro-perforated tear stubs and dynamic barcode/QR code verification.",
    basePrice: 499,
    pricingModel: "batch",
    baseQuantity: 100,
    rating: 4.8,
    reviewCount: 82,
    images: ["/images/cat-stickers.jpg"],
    isFeatured: false,
    tags: ["Tickets", "Event Entry", "Perforated", "Numbered", "Concert Pass"],
    sizeOptions: [
      { id: "tkt-std", label: "Standard Ticket (140 x 50 mm)", dimensions: "140 x 50 mm with 35mm stub", multiplier: 1.0, default: true },
      { id: "tkt-large", label: "VIP Pass Ticket (200 x 70 mm)", dimensions: "200 x 70 mm with 50mm stub", multiplier: 1.35 },
    ],
    materialOptions: [
      { id: "tkt-art-250", label: "250 GSM Gloss Art Cardstock", description: "Rigid ticket with punchy graphics", extraPricePerUnit: 0, default: true },
      { id: "tkt-holo", label: "300 GSM Card with Security Hologram Foil Strip", description: "Prevents ticket scalping and forgery", extraPricePerUnit: 1.5 },
    ],
    quantityTiers: [
      { quantity: 100, discountPercent: 0, default: true },
      { quantity: 250, discountPercent: 15 },
      { quantity: 500, discountPercent: 28 },
      { quantity: 1000, discountPercent: 42 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 50,
      hasFileUpload: true,
      uploadInstructions: "Provide starting serial number and event details.",
    },
    specifications: {
      "Perforation": "Precision micro-tooth perforation tears effortlessly by hand",
      "Numbering": "Dual sequential red numbering on ticket body & counterfoil stub",
      "Verification": "Compatible with standard smartphone QR code scanning apps",
      "Turnaround": "24 to 48 Hours",
    },
    features: [
      "Numbered counterfoil stub allows exact audit of gate entries",
      "Stapled in convenient booklets of 50 or 100 tickets with wrap covers",
      "Optional metallic security foil strip stops unauthorized color photocopies",
    ],
  },
  {
    id: "prod-ceremony-programs",
    slug: "ceremony-programs",
    name: "Folded Ceremony Itinerary & Program Booklets",
    categorySlug: "wedding-events",
    categoryName: "Wedding & Events",
    shortDescription: "Elegant ceremony order-of-service booklets and wedding ritual guide itineraries.",
    description: "Guide guests through cultural wedding rituals, sangeet performances, and conference keynotes. Beautifully formatted multi-panel folded guides printed on satin art paper.",
    basePrice: 599,
    pricingModel: "batch",
    baseQuantity: 50,
    rating: 4.8,
    reviewCount: 48,
    images: ["/images/cat-brochures.jpg"],
    isFeatured: false,
    tags: ["Ceremony Program", "Wedding Itinerary", "Order of Service", "Event Guide"],
    sizeOptions: [
      { id: "prog-dl", label: "Slim DL Itinerary (99 x 210 mm)", dimensions: "99 x 210 mm", multiplier: 1.0, default: true },
      { id: "prog-a5", label: "A5 Bi-Fold Booklet (148 x 210 mm folded)", dimensions: "Open 297 x 210 mm", multiplier: 1.3 },
    ],
    materialOptions: [
      { id: "prog-art", label: "200 GSM Heavy Satin Silk Art Paper", description: "Subtle sheen with zero glare", extraPricePerUnit: 0, default: true },
      { id: "prog-linen", label: "250 GSM Textured Natural Linen Paper", description: "Luxury tactile feel", extraPricePerUnit: 3 },
    ],
    quantityTiers: [
      { quantity: 50, discountPercent: 0, default: true },
      { quantity: 100, discountPercent: 12 },
      { quantity: 200, discountPercent: 22 },
      { quantity: 500, discountPercent: 36 },
    ],
    customizationRules: {
      hasCustomText: true,
      textPricePerChar: 0,
      freeCharLimit: 100,
      hasFileUpload: true,
    },
    specifications: {
      "Layout": "Single-card flat itinerary, 4-page bi-fold, or 6-page accordion fold",
      "Typography": "Crisp serif rendering for multifaith mantras and schedule timings",
      "Turnaround": "48 Hours",
    },
    features: [
      "Explains complex traditional customs to multicultural wedding attendees",
      "Detailed timeline breakdown of baraat, pheras, dinner, and reception",
      "Pre-scored folding prevents cracking along spine",
    ],
  },
];
