// =============================================================================
// StarPress Admin Panel — Mock Data
// Realistic printing e-commerce data for all admin sections
// =============================================================================

import type {
  AdminProduct,
  AdminCategory,
  AdminOrder,
  AdminCustomer,
  AdminDiscount,
  DashboardStats,
  AnalyticsData,
  FinanceSummary,
  FinanceTransaction,
  MarketingCampaign,
  ContentPage,
} from './types';

// --- Categories ---

export const MOCK_CATEGORIES: AdminCategory[] = [
  { id: 'cat-1', name: 'Business Printing', slug: 'business-printing', description: 'Corporate cards, letterheads, invoice books', productCount: 8, parentId: null },
  { id: 'cat-2', name: 'Marketing Materials', slug: 'marketing-materials', description: 'Flyers, brochures, posters, pamphlets', productCount: 5, parentId: null },
  { id: 'cat-3', name: 'Outdoor Advertising', slug: 'outdoor-advertising', description: 'Banners, standees, glow signs', productCount: 6, parentId: null },
  { id: 'cat-4', name: 'Stationery', slug: 'stationery', description: 'Notebooks, diaries, notepads, certificates', productCount: 4, parentId: null },
  { id: 'cat-5', name: 'Wedding & Events', slug: 'wedding-events', description: 'Wedding cards, invitations, event tickets', productCount: 3, parentId: null },
  { id: 'cat-6', name: 'Packaging', slug: 'packaging', description: 'Boxes, paper bags, hang tags', productCount: 4, parentId: null },
  { id: 'cat-7', name: 'Labels & Stickers', slug: 'labels-stickers', description: 'Vinyl stickers, bottle labels, barcode rolls', productCount: 5, parentId: null },
  { id: 'cat-8', name: 'Photo & Custom', slug: 'photo-custom-printing', description: 'Canvas prints, mugs, t-shirts, keychains', productCount: 4, parentId: null },
];

// --- Products ---

export const MOCK_PRODUCTS: AdminProduct[] = [
  {
    id: 'prod_001', sku: 'SP-BC-001', name: 'Premium Business Cards', slug: 'premium-business-cards',
    shortDescription: 'Professional 350gsm business cards with matte, glossy & foil finishes',
    description: '<p>Make lasting first impressions with our premium business cards. Printed on 350gsm art card stock with your choice of matte lamination, glossy UV coating, spot UV highlights, or luxurious gold/silver foil stamping.</p><ul><li>350gsm premium art card</li><li>Full color CMYK printing</li><li>Multiple finish options</li><li>Standard & custom sizes</li></ul>',
    categoryId: 'cat-1', categoryName: 'Business Printing', status: 'published',
    basePrice: 499, compareAtPrice: 799, costPerItem: 180, taxable: true,
    trackInventory: true, stockQuantity: 2500, lowStockThreshold: 100, allowBackorders: false,
    images: [
      { id: 'img_001', url: '/images/cat-business-cards.jpg', altText: 'Premium Business Cards', isPrimary: true, position: 0 },
    ],
    variantOptions: [
      { name: 'Size', values: ['Standard (3.5×2")', 'Square (2.5×2.5")', 'Mini (3×1")'] },
      { name: 'Finish', values: ['Matte', 'Glossy', 'Spot UV', 'Gold Foil'] },
    ],
    variants: [
      { id: 'v001', sku: 'SP-BC-001-STD-MAT', name: 'Standard / Matte', price: 499, compareAtPrice: 799, stock: 800, options: { Size: 'Standard (3.5×2")', Finish: 'Matte' }, status: 'active' },
      { id: 'v002', sku: 'SP-BC-001-STD-GLO', name: 'Standard / Glossy', price: 549, compareAtPrice: 849, stock: 600, options: { Size: 'Standard (3.5×2")', Finish: 'Glossy' }, status: 'active' },
      { id: 'v003', sku: 'SP-BC-001-STD-UV', name: 'Standard / Spot UV', price: 699, compareAtPrice: 999, stock: 400, options: { Size: 'Standard (3.5×2")', Finish: 'Spot UV' }, status: 'active' },
      { id: 'v004', sku: 'SP-BC-001-STD-FOI', name: 'Standard / Gold Foil', price: 899, compareAtPrice: 1299, stock: 200, options: { Size: 'Standard (3.5×2")', Finish: 'Gold Foil' }, status: 'active' },
    ],
    tags: ['business', 'cards', 'corporate', 'premium'], collections: ['Business Essentials', 'Best Sellers'], brand: 'Star Press',
    weight: 250, weightUnit: 'g', dimensions: { length: 9, width: 5.5, height: 3 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Premium Business Cards | Custom Printing', description: 'Order premium business cards with matte, glossy, spot UV and foil finish. Starting ₹499 for 100 cards.', slug: 'premium-business-cards' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: true,
    publishedAt: '2024-01-15T10:00:00Z', createdAt: '2024-01-10T08:30:00Z', updatedAt: '2024-09-15T14:20:00Z',
  },
  {
    id: 'prod_002', sku: 'SP-FL-001', name: 'A4 Flyers & Leaflets', slug: 'a4-flyers',
    shortDescription: 'High-impact A4 flyers on 130gsm art paper with vibrant color printing',
    description: '<p>Promote your business with eye-catching A4 flyers printed in full color on premium 130gsm art paper.</p>',
    categoryId: 'cat-2', categoryName: 'Marketing Materials', status: 'published',
    basePrice: 299, compareAtPrice: 499, costPerItem: 95, taxable: true,
    trackInventory: true, stockQuantity: 5000, lowStockThreshold: 200, allowBackorders: true,
    images: [{ id: 'img_002', url: '/images/cat-flyers.jpg', altText: 'A4 Flyers', isPrimary: true, position: 0 }],
    variantOptions: [{ name: 'Paper', values: ['130gsm Art Paper', '170gsm Art Paper', '250gsm Card'] }],
    variants: [
      { id: 'v005', sku: 'SP-FL-001-130', name: '130gsm Art Paper', price: 299, compareAtPrice: 499, stock: 2000, options: { Paper: '130gsm Art Paper' }, status: 'active' },
      { id: 'v006', sku: 'SP-FL-001-170', name: '170gsm Art Paper', price: 399, compareAtPrice: 599, stock: 1500, options: { Paper: '170gsm Art Paper' }, status: 'active' },
    ],
    tags: ['flyers', 'leaflets', 'marketing', 'promotion'], collections: ['Marketing Essentials'], brand: 'Star Press',
    weight: 500, weightUnit: 'g', dimensions: { length: 30, width: 21, height: 5 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'A4 Flyers & Leaflets | Star Press', description: 'Custom printed A4 flyers starting at ₹299 for 100 pieces.', slug: 'a4-flyers' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-02-01T10:00:00Z', createdAt: '2024-01-20T09:00:00Z', updatedAt: '2024-08-10T11:30:00Z',
  },
  {
    id: 'prod_003', sku: 'SP-VB-001', name: 'Vinyl Banners', slug: 'vinyl-banners',
    shortDescription: 'Weather-resistant vinyl banners with vivid eco-solvent printing',
    description: '<p>Durable outdoor vinyl banners with premium eco-solvent ink printing. UV-resistant and waterproof.</p>',
    categoryId: 'cat-3', categoryName: 'Outdoor Advertising', status: 'published',
    basePrice: 1499, compareAtPrice: 2499, costPerItem: 550, taxable: true,
    trackInventory: true, stockQuantity: 120, lowStockThreshold: 20, allowBackorders: false,
    images: [{ id: 'img_003', url: '/images/cat-banners.jpg', altText: 'Vinyl Banners', isPrimary: true, position: 0 }],
    variantOptions: [
      { name: 'Size', values: ['3×2 ft', '4×3 ft', '6×3 ft', '8×4 ft', 'Custom'] },
      { name: 'Finish', values: ['Standard', 'Premium Backlit'] },
    ],
    variants: [
      { id: 'v007', sku: 'SP-VB-001-3x2', name: '3×2 ft / Standard', price: 1499, compareAtPrice: 2499, stock: 40, options: { Size: '3×2 ft', Finish: 'Standard' }, status: 'active' },
      { id: 'v008', sku: 'SP-VB-001-6x3', name: '6×3 ft / Standard', price: 2999, compareAtPrice: 4499, stock: 30, options: { Size: '6×3 ft', Finish: 'Standard' }, status: 'active' },
    ],
    tags: ['banners', 'outdoor', 'vinyl', 'advertising'], collections: ['Outdoor Advertising'], brand: 'Star Press',
    weight: 2000, weightUnit: 'g', dimensions: { length: 100, width: 60, height: 10 }, requiresShipping: true, fragile: false, shippingClass: 'oversized',
    seo: { title: 'Vinyl Banners | Outdoor Advertising', description: 'Premium vinyl banners starting at ₹1,499. Weather-resistant outdoor printing.', slug: 'vinyl-banners' },
    visibility: { onlineStore: true, pos: false, shop: true }, featured: true,
    publishedAt: '2024-01-20T10:00:00Z', createdAt: '2024-01-18T08:00:00Z', updatedAt: '2024-09-01T09:15:00Z',
  },
  {
    id: 'prod_004', sku: 'SP-CS-001', name: 'Custom Die-Cut Stickers', slug: 'custom-stickers',
    shortDescription: 'Waterproof vinyl stickers in any custom shape with glossy/matte lamination',
    description: '<p>Premium die-cut stickers printed on waterproof vinyl with your choice of glossy or matte lamination.</p>',
    categoryId: 'cat-7', categoryName: 'Labels & Stickers', status: 'published',
    basePrice: 349, compareAtPrice: 599, costPerItem: 120, taxable: true,
    trackInventory: true, stockQuantity: 3200, lowStockThreshold: 150, allowBackorders: false,
    images: [{ id: 'img_004', url: '/images/prod-stickers.jpg', altText: 'Custom Stickers', isPrimary: true, position: 0 }],
    variantOptions: [
      { name: 'Size', values: ['2×2 inch', '3×3 inch', '4×4 inch', 'Custom'] },
      { name: 'Lamination', values: ['Glossy', 'Matte', 'None'] },
    ],
    variants: [
      { id: 'v009', sku: 'SP-CS-001-2x2-G', name: '2×2" / Glossy', price: 349, compareAtPrice: 599, stock: 1200, options: { Size: '2×2 inch', Lamination: 'Glossy' }, status: 'active' },
      { id: 'v010', sku: 'SP-CS-001-3x3-M', name: '3×3" / Matte', price: 449, compareAtPrice: 699, stock: 800, options: { Size: '3×3 inch', Lamination: 'Matte' }, status: 'active' },
    ],
    tags: ['stickers', 'die-cut', 'vinyl', 'waterproof', 'custom'], collections: ['Best Sellers', 'Labels & Stickers'], brand: 'Star Press',
    weight: 100, weightUnit: 'g', dimensions: null, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Custom Die-Cut Stickers | Star Press', description: 'Waterproof custom stickers in any shape. Starting ₹349 for 50 stickers.', slug: 'custom-stickers' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: true,
    publishedAt: '2024-02-10T10:00:00Z', createdAt: '2024-02-05T08:00:00Z', updatedAt: '2024-09-18T16:45:00Z',
  },
  {
    id: 'prod_005', sku: 'SP-LH-001', name: 'Corporate Letterheads', slug: 'letterheads',
    shortDescription: 'Professional letterheads on 100gsm woodfree paper with company branding',
    description: '<p>Elevate your business correspondence with professionally printed letterheads.</p>',
    categoryId: 'cat-1', categoryName: 'Business Printing', status: 'published',
    basePrice: 699, compareAtPrice: 999, costPerItem: 250, taxable: true,
    trackInventory: true, stockQuantity: 1800, lowStockThreshold: 100, allowBackorders: false,
    images: [], variantOptions: [], variants: [],
    tags: ['letterhead', 'corporate', 'stationery'], collections: ['Business Essentials'], brand: 'Star Press',
    weight: 400, weightUnit: 'g', dimensions: { length: 30, width: 21, height: 4 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Corporate Letterheads | Star Press', description: 'Professional letterheads for your business starting at ₹699.', slug: 'letterheads' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-03-01T10:00:00Z', createdAt: '2024-02-25T09:00:00Z', updatedAt: '2024-07-20T10:00:00Z',
  },
  {
    id: 'prod_006', sku: 'SP-BR-001', name: 'Tri-Fold Brochures', slug: 'brochures',
    shortDescription: 'Eye-catching tri-fold brochures on 170gsm art paper',
    description: '<p>Professional tri-fold brochures perfect for product showcases, services, and events.</p>',
    categoryId: 'cat-2', categoryName: 'Marketing Materials', status: 'published',
    basePrice: 599, compareAtPrice: 899, costPerItem: 200, taxable: true,
    trackInventory: true, stockQuantity: 2200, lowStockThreshold: 100, allowBackorders: false,
    images: [{ id: 'img_006', url: '/images/cat-brochures.jpg', altText: 'Brochures', isPrimary: true, position: 0 }],
    variantOptions: [{ name: 'Paper', values: ['170gsm Art Paper', '250gsm Art Card'] }],
    variants: [
      { id: 'v011', sku: 'SP-BR-001-170', name: '170gsm Art Paper', price: 599, compareAtPrice: 899, stock: 1500, options: { Paper: '170gsm Art Paper' }, status: 'active' },
    ],
    tags: ['brochures', 'tri-fold', 'marketing'], collections: ['Marketing Essentials'], brand: 'Star Press',
    weight: 350, weightUnit: 'g', dimensions: { length: 30, width: 21, height: 4 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Tri-Fold Brochures | Star Press', description: 'Custom tri-fold brochures starting at ₹599.', slug: 'brochures' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-02-15T10:00:00Z', createdAt: '2024-02-12T08:00:00Z', updatedAt: '2024-08-25T12:00:00Z',
  },
  {
    id: 'prod_007', sku: 'SP-WC-001', name: 'Luxury Wedding Cards', slug: 'wedding-cards',
    shortDescription: 'Foil-pressed wedding invitations on premium 350gsm textured stock',
    description: '<p>Exquisite foil-pressed wedding invitations crafted on luxurious textured card stock.</p>',
    categoryId: 'cat-5', categoryName: 'Wedding & Events', status: 'published',
    basePrice: 1999, compareAtPrice: 3499, costPerItem: 750, taxable: true,
    trackInventory: true, stockQuantity: 450, lowStockThreshold: 50, allowBackorders: false,
    images: [{ id: 'img_007', url: '/images/cat-stickers.jpg', altText: 'Wedding Cards', isPrimary: true, position: 0 }],
    variantOptions: [
      { name: 'Style', values: ['Classic Foil', 'Modern Minimal', 'Royal Ornate', 'Floral Elegance'] },
      { name: 'Foil', values: ['Gold', 'Silver', 'Rose Gold', 'None'] },
    ],
    variants: [
      { id: 'v012', sku: 'SP-WC-001-CLS-GLD', name: 'Classic / Gold Foil', price: 1999, compareAtPrice: 3499, stock: 150, options: { Style: 'Classic Foil', Foil: 'Gold' }, status: 'active' },
      { id: 'v013', sku: 'SP-WC-001-ROY-SLV', name: 'Royal Ornate / Silver Foil', price: 2499, compareAtPrice: 3999, stock: 100, options: { Style: 'Royal Ornate', Foil: 'Silver' }, status: 'active' },
    ],
    tags: ['wedding', 'invitations', 'foil', 'premium', 'luxury'], collections: ['Wedding Collection'], brand: 'Star Press',
    weight: 600, weightUnit: 'g', dimensions: { length: 25, width: 18, height: 5 }, requiresShipping: true, fragile: true, shippingClass: 'fragile',
    seo: { title: 'Luxury Wedding Cards | Star Press', description: 'Stunning foil-pressed wedding invitations starting at ₹1,999 for 50 cards.', slug: 'wedding-cards' },
    visibility: { onlineStore: true, pos: false, shop: true }, featured: true,
    publishedAt: '2024-03-01T10:00:00Z', createdAt: '2024-02-28T09:00:00Z', updatedAt: '2024-09-10T15:30:00Z',
  },
  {
    id: 'prod_008', sku: 'SP-PB-001', name: 'Custom Packaging Boxes', slug: 'packaging-boxes',
    shortDescription: 'Custom printed corrugated and rigid boxes for product packaging',
    description: '<p>Professional custom packaging solutions for your products. Available in corrugated and rigid box options.</p>',
    categoryId: 'cat-6', categoryName: 'Packaging', status: 'published',
    basePrice: 2499, compareAtPrice: 3999, costPerItem: 900, taxable: true,
    trackInventory: true, stockQuantity: 340, lowStockThreshold: 30, allowBackorders: true,
    images: [{ id: 'img_008', url: '/images/cat-gifts.jpg', altText: 'Packaging Boxes', isPrimary: true, position: 0 }],
    variantOptions: [
      { name: 'Material', values: ['Corrugated (3-ply)', 'Corrugated (5-ply)', 'Rigid Board'] },
      { name: 'Print', values: ['1-Color', 'Full Color', 'Full Color + Lamination'] },
    ],
    variants: [
      { id: 'v014', sku: 'SP-PB-001-3P-1C', name: 'Corrugated 3-ply / 1-Color', price: 2499, compareAtPrice: 3999, stock: 150, options: { Material: 'Corrugated (3-ply)', Print: '1-Color' }, status: 'active' },
    ],
    tags: ['packaging', 'boxes', 'custom', 'corrugated'], collections: ['Packaging Solutions'], brand: 'Star Press',
    weight: 1500, weightUnit: 'g', dimensions: { length: 40, width: 30, height: 25 }, requiresShipping: true, fragile: false, shippingClass: 'oversized',
    seo: { title: 'Custom Packaging Boxes | Star Press', description: 'Custom printed packaging boxes starting at ₹2,499 for 50 boxes.', slug: 'packaging-boxes' },
    visibility: { onlineStore: true, pos: false, shop: true }, featured: false,
    publishedAt: '2024-03-15T10:00:00Z', createdAt: '2024-03-10T08:00:00Z', updatedAt: '2024-09-05T11:00:00Z',
  },
  {
    id: 'prod_009', sku: 'SP-TS-001', name: 'Custom T-Shirt Printing', slug: 't-shirt-printing',
    shortDescription: 'DTG and screen-printed custom t-shirts in cotton and polyblend',
    description: '<p>High-quality custom t-shirt printing using DTG (Direct to Garment) and screen printing techniques.</p>',
    categoryId: 'cat-8', categoryName: 'Photo & Custom', status: 'published',
    basePrice: 399, compareAtPrice: 699, costPerItem: 150, taxable: true,
    trackInventory: true, stockQuantity: 1200, lowStockThreshold: 50, allowBackorders: false,
    images: [{ id: 'img_009', url: '/images/promo-banner.jpg', altText: 'T-Shirt Printing', isPrimary: true, position: 0 }],
    variantOptions: [
      { name: 'Size', values: ['S', 'M', 'L', 'XL', 'XXL'] },
      { name: 'Color', values: ['White', 'Black', 'Navy', 'Grey'] },
      { name: 'Fabric', values: ['100% Cotton', 'Cotton-Poly Blend'] },
    ],
    variants: [
      { id: 'v015', sku: 'SP-TS-001-M-WHT', name: 'M / White / Cotton', price: 399, compareAtPrice: 699, stock: 200, options: { Size: 'M', Color: 'White', Fabric: '100% Cotton' }, status: 'active' },
      { id: 'v016', sku: 'SP-TS-001-L-BLK', name: 'L / Black / Cotton', price: 399, compareAtPrice: 699, stock: 180, options: { Size: 'L', Color: 'Black', Fabric: '100% Cotton' }, status: 'active' },
    ],
    tags: ['t-shirts', 'custom', 'apparel', 'DTG', 'screen-print'], collections: ['Custom Merch'], brand: 'Star Press',
    weight: 200, weightUnit: 'g', dimensions: null, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Custom T-Shirt Printing | Star Press', description: 'Custom printed t-shirts starting at ₹399. DTG and screen printing available.', slug: 't-shirt-printing' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-04-01T10:00:00Z', createdAt: '2024-03-28T08:00:00Z', updatedAt: '2024-09-12T09:30:00Z',
  },
  {
    id: 'prod_010', sku: 'SP-NB-001', name: 'Branded Notebooks', slug: 'notebooks',
    shortDescription: 'Custom hardbound and softcover notebooks with logo embossing',
    description: '<p>Professional branded notebooks perfect for corporate gifting and events.</p>',
    categoryId: 'cat-4', categoryName: 'Stationery', status: 'published',
    basePrice: 249, compareAtPrice: 449, costPerItem: 90, taxable: true,
    trackInventory: true, stockQuantity: 4000, lowStockThreshold: 200, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Cover', values: ['Hardbound', 'Softcover', 'Spiral'] }],
    variants: [
      { id: 'v017', sku: 'SP-NB-001-HB', name: 'Hardbound', price: 249, compareAtPrice: 449, stock: 2000, options: { Cover: 'Hardbound' }, status: 'active' },
    ],
    tags: ['notebooks', 'stationery', 'corporate', 'branded'], collections: ['Corporate Gifts', 'Stationery'], brand: 'Star Press',
    weight: 300, weightUnit: 'g', dimensions: { length: 21, width: 15, height: 2 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Branded Notebooks | Star Press', description: 'Custom branded notebooks starting at ₹249.', slug: 'notebooks' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-04-15T10:00:00Z', createdAt: '2024-04-10T08:00:00Z', updatedAt: '2024-08-30T14:00:00Z',
  },
  {
    id: 'prod_011', sku: 'SP-SD-001', name: 'Retractable Standees', slug: 'standees',
    shortDescription: 'Roll-up retractable standees for exhibitions, events and promotions',
    description: '<p>Professional retractable banner standees perfect for trade shows, events, and point-of-sale displays.</p>',
    categoryId: 'cat-3', categoryName: 'Outdoor Advertising', status: 'published',
    basePrice: 1299, compareAtPrice: 1999, costPerItem: 480, taxable: true,
    trackInventory: true, stockQuantity: 85, lowStockThreshold: 15, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Size', values: ['2.5×6 ft', '3×6 ft', '4×6 ft'] }],
    variants: [
      { id: 'v018', sku: 'SP-SD-001-3x6', name: '3×6 ft', price: 1299, compareAtPrice: 1999, stock: 45, options: { Size: '3×6 ft' }, status: 'active' },
    ],
    tags: ['standees', 'roll-up', 'exhibition', 'events'], collections: ['Outdoor Advertising'], brand: 'Star Press',
    weight: 3000, weightUnit: 'g', dimensions: { length: 90, width: 12, height: 12 }, requiresShipping: true, fragile: true, shippingClass: 'oversized',
    seo: { title: 'Retractable Standees | Star Press', description: 'Roll-up standees starting at ₹1,299.', slug: 'standees' },
    visibility: { onlineStore: true, pos: false, shop: true }, featured: false,
    publishedAt: '2024-05-01T10:00:00Z', createdAt: '2024-04-28T08:00:00Z', updatedAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'prod_012', sku: 'SP-BL-001', name: 'Bottle Labels', slug: 'bottle-labels',
    shortDescription: 'Waterproof adhesive bottle labels with custom shapes and sizes',
    description: '<p>Professional bottle labels printed on waterproof vinyl or BOPP material.</p>',
    categoryId: 'cat-7', categoryName: 'Labels & Stickers', status: 'published',
    basePrice: 449, compareAtPrice: 749, costPerItem: 160, taxable: true,
    trackInventory: true, stockQuantity: 2800, lowStockThreshold: 200, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Material', values: ['Vinyl', 'BOPP', 'Paper'] }],
    variants: [
      { id: 'v019', sku: 'SP-BL-001-VIN', name: 'Vinyl', price: 449, compareAtPrice: 749, stock: 1200, options: { Material: 'Vinyl' }, status: 'active' },
    ],
    tags: ['labels', 'bottle', 'waterproof', 'adhesive'], collections: ['Labels & Stickers'], brand: 'Star Press',
    weight: 150, weightUnit: 'g', dimensions: null, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Bottle Labels | Star Press', description: 'Custom bottle labels starting at ₹449.', slug: 'bottle-labels' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-05-15T10:00:00Z', createdAt: '2024-05-10T08:00:00Z', updatedAt: '2024-08-15T11:00:00Z',
  },
  {
    id: 'prod_013', sku: 'SP-MP-001', name: 'Custom Ceramic Mugs', slug: 'mug-printing',
    shortDescription: 'Sublimation printed ceramic mugs for corporate gifts and personalization',
    description: '<p>High-quality sublimation printed ceramic mugs. Perfect for corporate gifts, events, and personal use.</p>',
    categoryId: 'cat-8', categoryName: 'Photo & Custom', status: 'published',
    basePrice: 299, compareAtPrice: 499, costPerItem: 110, taxable: true,
    trackInventory: true, stockQuantity: 600, lowStockThreshold: 30, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Type', values: ['White Ceramic', 'Magic (Color Change)', 'Inner Color'] }],
    variants: [
      { id: 'v020', sku: 'SP-MP-001-WHT', name: 'White Ceramic', price: 299, compareAtPrice: 499, stock: 300, options: { Type: 'White Ceramic' }, status: 'active' },
      { id: 'v021', sku: 'SP-MP-001-MAG', name: 'Magic (Color Change)', price: 449, compareAtPrice: 699, stock: 150, options: { Type: 'Magic (Color Change)' }, status: 'active' },
    ],
    tags: ['mugs', 'ceramic', 'sublimation', 'gifts', 'custom'], collections: ['Custom Merch', 'Corporate Gifts'], brand: 'Star Press',
    weight: 350, weightUnit: 'g', dimensions: { length: 12, width: 10, height: 10 }, requiresShipping: true, fragile: true, shippingClass: 'fragile',
    seo: { title: 'Custom Ceramic Mugs | Star Press', description: 'Personalized ceramic mugs starting at ₹299.', slug: 'mug-printing' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-06-01T10:00:00Z', createdAt: '2024-05-28T08:00:00Z', updatedAt: '2024-09-08T13:00:00Z',
  },
  {
    id: 'prod_014', sku: 'SP-EN-001', name: 'Business Envelopes', slug: 'envelopes',
    shortDescription: 'Custom printed envelopes in DL, C5, and C4 sizes',
    description: '<p>Professional business envelopes with custom printing for your brand correspondence.</p>',
    categoryId: 'cat-1', categoryName: 'Business Printing', status: 'published',
    basePrice: 399, compareAtPrice: 649, costPerItem: 140, taxable: true,
    trackInventory: true, stockQuantity: 3500, lowStockThreshold: 150, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Size', values: ['DL (110×220mm)', 'C5 (162×229mm)', 'C4 (229×324mm)'] }],
    variants: [
      { id: 'v022', sku: 'SP-EN-001-DL', name: 'DL Size', price: 399, compareAtPrice: 649, stock: 1500, options: { Size: 'DL (110×220mm)' }, status: 'active' },
    ],
    tags: ['envelopes', 'business', 'corporate'], collections: ['Business Essentials'], brand: 'Star Press',
    weight: 200, weightUnit: 'g', dimensions: { length: 25, width: 18, height: 3 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Business Envelopes | Star Press', description: 'Custom printed business envelopes starting at ₹399.', slug: 'envelopes' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-03-20T10:00:00Z', createdAt: '2024-03-18T08:00:00Z', updatedAt: '2024-07-10T10:00:00Z',
  },
  {
    id: 'prod_015', sku: 'SP-GS-001', name: 'LED Glow Sign Boards', slug: 'glow-signs',
    shortDescription: 'Illuminated acrylic glow sign boards with LED backlighting',
    description: '<p>Professional LED glow sign boards for shops, offices, and commercial spaces.</p>',
    categoryId: 'cat-3', categoryName: 'Outdoor Advertising', status: 'draft',
    basePrice: 4999, compareAtPrice: 7999, costPerItem: 2200, taxable: true,
    trackInventory: true, stockQuantity: 25, lowStockThreshold: 5, allowBackorders: true,
    images: [], variantOptions: [{ name: 'Size', values: ['2×1 ft', '3×1.5 ft', '4×2 ft', 'Custom'] }],
    variants: [
      { id: 'v023', sku: 'SP-GS-001-3x1', name: '3×1.5 ft', price: 4999, compareAtPrice: 7999, stock: 12, options: { Size: '3×1.5 ft' }, status: 'active' },
    ],
    tags: ['glow-signs', 'LED', 'signage', 'illuminated'], collections: ['Outdoor Advertising'], brand: 'Star Press',
    weight: 5000, weightUnit: 'g', dimensions: { length: 100, width: 50, height: 15 }, requiresShipping: true, fragile: true, shippingClass: 'fragile',
    seo: { title: 'LED Glow Sign Boards | Star Press', description: 'Custom LED glow sign boards starting at ₹4,999.', slug: 'glow-signs' },
    visibility: { onlineStore: false, pos: false, shop: false }, featured: false,
    publishedAt: null, createdAt: '2024-08-01T08:00:00Z', updatedAt: '2024-09-20T10:00:00Z',
  },
  {
    id: 'prod_016', sku: 'SP-BB-001', name: 'Duplicate Bill Books', slug: 'bill-books',
    shortDescription: 'Carbonless NCR duplicate and triplicate bill books',
    description: '<p>Professional carbonless NCR bill books for invoicing and receipts.</p>',
    categoryId: 'cat-1', categoryName: 'Business Printing', status: 'published',
    basePrice: 349, compareAtPrice: 549, costPerItem: 120, taxable: true,
    trackInventory: true, stockQuantity: 2100, lowStockThreshold: 100, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Type', values: ['Duplicate (2-part)', 'Triplicate (3-part)'] }],
    variants: [
      { id: 'v024', sku: 'SP-BB-001-DUP', name: 'Duplicate', price: 349, compareAtPrice: 549, stock: 1200, options: { Type: 'Duplicate (2-part)' }, status: 'active' },
      { id: 'v025', sku: 'SP-BB-001-TRI', name: 'Triplicate', price: 449, compareAtPrice: 699, stock: 600, options: { Type: 'Triplicate (3-part)' }, status: 'active' },
    ],
    tags: ['bill-books', 'NCR', 'carbonless', 'invoicing'], collections: ['Business Essentials'], brand: 'Star Press',
    weight: 400, weightUnit: 'g', dimensions: { length: 22, width: 14, height: 3 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Bill Books | Star Press', description: 'Carbonless NCR bill books starting at ₹349.', slug: 'bill-books' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-04-10T10:00:00Z', createdAt: '2024-04-08T08:00:00Z', updatedAt: '2024-08-05T09:00:00Z',
  },
  {
    id: 'prod_017', sku: 'SP-PS-001', name: 'Posters (A3/A2/A1)', slug: 'posters',
    shortDescription: 'Large format posters on glossy/matte art paper',
    description: '<p>High-quality large format poster printing for promotions, events, and wall decor.</p>',
    categoryId: 'cat-2', categoryName: 'Marketing Materials', status: 'published',
    basePrice: 199, compareAtPrice: 349, costPerItem: 65, taxable: true,
    trackInventory: true, stockQuantity: 6000, lowStockThreshold: 300, allowBackorders: true,
    images: [], variantOptions: [
      { name: 'Size', values: ['A3 (12×18")', 'A2 (18×24")', 'A1 (24×36")'] },
      { name: 'Paper', values: ['130gsm Glossy', '170gsm Matte', '250gsm Art Card'] },
    ],
    variants: [
      { id: 'v026', sku: 'SP-PS-001-A3-GLO', name: 'A3 / Glossy', price: 199, compareAtPrice: 349, stock: 2500, options: { Size: 'A3 (12×18")', Paper: '130gsm Glossy' }, status: 'active' },
      { id: 'v027', sku: 'SP-PS-001-A2-MAT', name: 'A2 / Matte', price: 349, compareAtPrice: 549, stock: 1500, options: { Size: 'A2 (18×24")', Paper: '170gsm Matte' }, status: 'active' },
    ],
    tags: ['posters', 'large-format', 'promotional'], collections: ['Marketing Essentials'], brand: 'Star Press',
    weight: 300, weightUnit: 'g', dimensions: { length: 46, width: 33, height: 2 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Custom Posters | Star Press', description: 'Custom poster printing starting at ₹199.', slug: 'posters' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-02-20T10:00:00Z', createdAt: '2024-02-18T08:00:00Z', updatedAt: '2024-08-20T11:00:00Z',
  },
  {
    id: 'prod_018', sku: 'SP-CPB-001', name: 'Custom Paper Bags', slug: 'custom-paper-bags',
    shortDescription: 'Branded kraft and art paper bags for retail and gifting',
    description: '<p>Eco-friendly custom paper bags for retail packaging, events, and corporate gifting.</p>',
    categoryId: 'cat-6', categoryName: 'Packaging', status: 'draft',
    basePrice: 799, compareAtPrice: 1299, costPerItem: 300, taxable: true,
    trackInventory: true, stockQuantity: 800, lowStockThreshold: 50, allowBackorders: false,
    images: [], variantOptions: [
      { name: 'Material', values: ['Brown Kraft', 'White Art Paper', 'Luxury Laminated'] },
      { name: 'Size', values: ['Small (8×6×3")', 'Medium (10×8×4")', 'Large (14×10×5")'] },
    ],
    variants: [
      { id: 'v028', sku: 'SP-CPB-001-KFT-M', name: 'Kraft / Medium', price: 799, compareAtPrice: 1299, stock: 400, options: { Material: 'Brown Kraft', Size: 'Medium (10×8×4")' }, status: 'active' },
    ],
    tags: ['paper-bags', 'packaging', 'eco-friendly', 'kraft'], collections: ['Packaging Solutions'], brand: 'Star Press',
    weight: 500, weightUnit: 'g', dimensions: { length: 30, width: 25, height: 15 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Custom Paper Bags | Star Press', description: 'Branded paper bags starting at ₹799.', slug: 'custom-paper-bags' },
    visibility: { onlineStore: false, pos: false, shop: false }, featured: false,
    publishedAt: null, createdAt: '2024-07-15T08:00:00Z', updatedAt: '2024-09-19T16:00:00Z',
  },
  {
    id: 'prod_019', sku: 'SP-CP-001', name: 'Canvas Photo Prints', slug: 'canvas-prints',
    shortDescription: 'Gallery-quality canvas prints with wooden frame stretching',
    description: '<p>Museum-quality canvas prints on premium cotton canvas with wooden stretcher frame.</p>',
    categoryId: 'cat-8', categoryName: 'Photo & Custom', status: 'published',
    basePrice: 899, compareAtPrice: 1499, costPerItem: 350, taxable: true,
    trackInventory: true, stockQuantity: 180, lowStockThreshold: 15, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Size', values: ['8×10"', '12×16"', '16×20"', '20×30"', '24×36"'] }],
    variants: [
      { id: 'v029', sku: 'SP-CP-001-12x16', name: '12×16"', price: 899, compareAtPrice: 1499, stock: 60, options: { Size: '12×16"' }, status: 'active' },
      { id: 'v030', sku: 'SP-CP-001-20x30', name: '20×30"', price: 1699, compareAtPrice: 2499, stock: 40, options: { Size: '20×30"' }, status: 'active' },
    ],
    tags: ['canvas', 'photo-prints', 'wall-art', 'gallery'], collections: ['Custom Merch'], brand: 'Star Press',
    weight: 800, weightUnit: 'g', dimensions: { length: 50, width: 40, height: 5 }, requiresShipping: true, fragile: true, shippingClass: 'fragile',
    seo: { title: 'Canvas Photo Prints | Star Press', description: 'Gallery-quality canvas prints starting at ₹899.', slug: 'canvas-prints' },
    visibility: { onlineStore: true, pos: false, shop: true }, featured: false,
    publishedAt: '2024-06-15T10:00:00Z', createdAt: '2024-06-10T08:00:00Z', updatedAt: '2024-09-14T12:00:00Z',
  },
  {
    id: 'prod_020', sku: 'SP-FX-001', name: 'Flex Banner Printing', slug: 'flex-printing',
    shortDescription: 'Large format flex banners for hoardings and outdoor advertising',
    description: '<p>High-resolution flex banner printing for large format outdoor advertising and hoardings.</p>',
    categoryId: 'cat-3', categoryName: 'Outdoor Advertising', status: 'published',
    basePrice: 999, compareAtPrice: 1699, costPerItem: 350, taxable: true,
    trackInventory: true, stockQuantity: 0, lowStockThreshold: 10, allowBackorders: true,
    images: [], variantOptions: [{ name: 'Material', values: ['Star Flex (280gsm)', 'Eco Flex (340gsm)', 'Premium (440gsm)'] }],
    variants: [
      { id: 'v031', sku: 'SP-FX-001-280', name: 'Star Flex 280gsm', price: 999, compareAtPrice: 1699, stock: 0, options: { Material: 'Star Flex (280gsm)' }, status: 'active' },
    ],
    tags: ['flex', 'banners', 'hoardings', 'outdoor'], collections: ['Outdoor Advertising'], brand: 'Star Press',
    weight: 3000, weightUnit: 'g', dimensions: null, requiresShipping: true, fragile: false, shippingClass: 'oversized',
    seo: { title: 'Flex Banner Printing | Star Press', description: 'Flex banner printing starting at ₹999.', slug: 'flex-printing' },
    visibility: { onlineStore: true, pos: false, shop: true }, featured: false,
    publishedAt: '2024-03-10T10:00:00Z', createdAt: '2024-03-08T08:00:00Z', updatedAt: '2024-09-22T08:00:00Z',
  },
  {
    id: 'prod_021', sku: 'SP-IC-001', name: 'Invitation Cards', slug: 'invitation-cards',
    shortDescription: 'Custom event invitations with premium paper and finish options',
    description: '<p>Beautifully designed invitation cards for birthdays, anniversaries, and corporate events.</p>',
    categoryId: 'cat-5', categoryName: 'Wedding & Events', status: 'archived',
    basePrice: 599, compareAtPrice: 999, costPerItem: 200, taxable: true,
    trackInventory: true, stockQuantity: 300, lowStockThreshold: 25, allowBackorders: false,
    images: [], variantOptions: [], variants: [],
    tags: ['invitations', 'events', 'cards'], collections: ['Wedding Collection'], brand: 'Star Press',
    weight: 250, weightUnit: 'g', dimensions: { length: 20, width: 15, height: 3 }, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Invitation Cards | Star Press', description: 'Custom invitation cards starting at ₹599.', slug: 'invitation-cards' },
    visibility: { onlineStore: false, pos: false, shop: false }, featured: false,
    publishedAt: '2024-01-05T10:00:00Z', createdAt: '2024-01-02T08:00:00Z', updatedAt: '2024-06-30T10:00:00Z',
  },
  {
    id: 'prod_022', sku: 'SP-HT-001', name: 'Hang Tags', slug: 'hang-tags',
    shortDescription: 'Custom printed hang tags for clothing and retail products',
    description: '<p>Premium custom hang tags for clothing brands, retail products, and artisan goods.</p>',
    categoryId: 'cat-6', categoryName: 'Packaging', status: 'published',
    basePrice: 249, compareAtPrice: 449, costPerItem: 80, taxable: true,
    trackInventory: true, stockQuantity: 5500, lowStockThreshold: 300, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Paper', values: ['300gsm Art Card', '350gsm Kraft', '400gsm Textured'] }],
    variants: [
      { id: 'v032', sku: 'SP-HT-001-ART', name: '300gsm Art Card', price: 249, compareAtPrice: 449, stock: 2500, options: { Paper: '300gsm Art Card' }, status: 'active' },
    ],
    tags: ['hang-tags', 'clothing', 'retail', 'branding'], collections: ['Packaging Solutions'], brand: 'Star Press',
    weight: 100, weightUnit: 'g', dimensions: null, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Custom Hang Tags | Star Press', description: 'Custom hang tags starting at ₹249.', slug: 'hang-tags' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-05-20T10:00:00Z', createdAt: '2024-05-18T08:00:00Z', updatedAt: '2024-09-03T11:00:00Z',
  },
  {
    id: 'prod_023', sku: 'SP-ID-001', name: 'PVC ID Cards', slug: 'id-cards',
    shortDescription: 'Durable PVC ID cards with photo, barcode, and QR code printing',
    description: '<p>Professional PVC ID cards for employees, students, and members.</p>',
    categoryId: 'cat-4', categoryName: 'Stationery', status: 'published',
    basePrice: 149, compareAtPrice: 299, costPerItem: 50, taxable: true,
    trackInventory: true, stockQuantity: 8000, lowStockThreshold: 500, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Type', values: ['Standard PVC', 'Smart Card (RFID)', 'Proximity'] }],
    variants: [
      { id: 'v033', sku: 'SP-ID-001-STD', name: 'Standard PVC', price: 149, compareAtPrice: 299, stock: 5000, options: { Type: 'Standard PVC' }, status: 'active' },
      { id: 'v034', sku: 'SP-ID-001-RFID', name: 'Smart Card (RFID)', price: 349, compareAtPrice: 599, stock: 1500, options: { Type: 'Smart Card (RFID)' }, status: 'active' },
    ],
    tags: ['id-cards', 'PVC', 'employee', 'corporate'], collections: ['Stationery', 'Corporate Gifts'], brand: 'Star Press',
    weight: 50, weightUnit: 'g', dimensions: null, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'PVC ID Cards | Star Press', description: 'PVC ID cards starting at ₹149.', slug: 'id-cards' },
    visibility: { onlineStore: true, pos: true, shop: true }, featured: false,
    publishedAt: '2024-06-20T10:00:00Z', createdAt: '2024-06-18T08:00:00Z', updatedAt: '2024-09-16T14:00:00Z',
  },
  {
    id: 'prod_024', sku: 'SP-KC-001', name: 'Custom Keychains', slug: 'keychain-printing',
    shortDescription: 'Acrylic, metal, and wooden custom printed keychains',
    description: '<p>Custom keychains in acrylic, metal, and wooden materials. Perfect for promotions and gifts.</p>',
    categoryId: 'cat-8', categoryName: 'Photo & Custom', status: 'draft',
    basePrice: 99, compareAtPrice: 199, costPerItem: 35, taxable: true,
    trackInventory: true, stockQuantity: 3000, lowStockThreshold: 200, allowBackorders: false,
    images: [], variantOptions: [{ name: 'Material', values: ['Acrylic', 'Metal', 'Wooden'] }],
    variants: [
      { id: 'v035', sku: 'SP-KC-001-ACR', name: 'Acrylic', price: 99, compareAtPrice: 199, stock: 1500, options: { Material: 'Acrylic' }, status: 'active' },
    ],
    tags: ['keychains', 'custom', 'promotional', 'gifts'], collections: ['Custom Merch'], brand: 'Star Press',
    weight: 30, weightUnit: 'g', dimensions: null, requiresShipping: true, fragile: false, shippingClass: 'standard',
    seo: { title: 'Custom Keychains | Star Press', description: 'Custom keychains starting at ₹99.', slug: 'keychain-printing' },
    visibility: { onlineStore: false, pos: false, shop: false }, featured: false,
    publishedAt: null, createdAt: '2024-08-10T08:00:00Z', updatedAt: '2024-09-21T09:00:00Z',
  },
  {
    id: 'prod_025', sku: 'SP-NB-002', name: 'Neon Sign Boards', slug: 'neon-boards',
    shortDescription: 'Custom LED neon signs for cafes, restaurants, and commercial spaces',
    description: '<p>Custom LED neon sign boards that mimic the classic neon look with modern LED technology.</p>',
    categoryId: 'cat-3', categoryName: 'Outdoor Advertising', status: 'draft',
    basePrice: 3499, compareAtPrice: 5999, costPerItem: 1500, taxable: true,
    trackInventory: true, stockQuantity: 8, lowStockThreshold: 3, allowBackorders: true,
    images: [], variantOptions: [{ name: 'Size', values: ['Small (12")', 'Medium (18")', 'Large (24")', 'Custom'] }],
    variants: [
      { id: 'v036', sku: 'SP-NB-002-MED', name: 'Medium 18"', price: 3499, compareAtPrice: 5999, stock: 4, options: { Size: 'Medium (18")' }, status: 'active' },
    ],
    tags: ['neon', 'LED', 'signage', 'cafe', 'restaurant'], collections: ['Outdoor Advertising'], brand: 'Star Press',
    weight: 2000, weightUnit: 'g', dimensions: { length: 50, width: 30, height: 8 }, requiresShipping: true, fragile: true, shippingClass: 'fragile',
    seo: { title: 'LED Neon Sign Boards | Star Press', description: 'Custom LED neon signs starting at ₹3,499.', slug: 'neon-boards' },
    visibility: { onlineStore: false, pos: false, shop: false }, featured: false,
    publishedAt: null, createdAt: '2024-09-01T08:00:00Z', updatedAt: '2024-09-22T10:00:00Z',
  },
];

// --- Orders ---

export const MOCK_ORDERS: AdminOrder[] = [
  {
    id: 'ord_001', orderNumber: 'SP-2409-001', customerName: 'Rajesh Sharma', customerEmail: 'rajesh.sharma@example.com', customerPhone: '+91 98765 43210',
    date: '2024-09-22T08:30:00Z',
    items: [
      { id: 'oi_001', productId: 'prod_001', productName: 'Premium Business Cards', sku: 'SP-BC-001-STD-MAT', quantity: 2, unitPrice: 499, total: 998, image: '/images/cat-business-cards.jpg' },
      { id: 'oi_002', productId: 'prod_005', productName: 'Corporate Letterheads', sku: 'SP-LH-001', quantity: 1, unitPrice: 699, total: 699, image: '' },
    ],
    itemCount: 3, subtotal: 1697, tax: 305, shipping: 99, discount: 0, total: 2101,
    paymentStatus: 'paid', fulfillmentStatus: 'unfulfilled', status: 'processing',
    shippingAddress: '42, Connaught Place, New Delhi 110001', notes: 'Urgent delivery needed',
  },
  {
    id: 'ord_002', orderNumber: 'SP-2409-002', customerName: 'Priya Patel', customerEmail: 'priya.patel@company.in', customerPhone: '+91 87654 32109',
    date: '2024-09-21T14:15:00Z',
    items: [
      { id: 'oi_003', productId: 'prod_007', productName: 'Luxury Wedding Cards', sku: 'SP-WC-001-CLS-GLD', quantity: 5, unitPrice: 1999, total: 9995, image: '' },
    ],
    itemCount: 5, subtotal: 9995, tax: 1799, shipping: 199, discount: 500, total: 11493,
    paymentStatus: 'paid', fulfillmentStatus: 'partial', status: 'processing',
    shippingAddress: '15, MG Road, Bangalore 560001', notes: 'Wedding on Oct 15. Deliver by Oct 5.',
  },
  {
    id: 'ord_003', orderNumber: 'SP-2409-003', customerName: 'Amit Kumar', customerEmail: 'amit.k@startup.io', customerPhone: '+91 76543 21098',
    date: '2024-09-20T10:45:00Z',
    items: [
      { id: 'oi_004', productId: 'prod_004', productName: 'Custom Die-Cut Stickers', sku: 'SP-CS-001-2x2-G', quantity: 10, unitPrice: 349, total: 3490, image: '' },
      { id: 'oi_005', productId: 'prod_009', productName: 'Custom T-Shirt Printing', sku: 'SP-TS-001-M-WHT', quantity: 25, unitPrice: 399, total: 9975, image: '' },
    ],
    itemCount: 35, subtotal: 13465, tax: 2424, shipping: 299, discount: 1347, total: 14841,
    paymentStatus: 'paid', fulfillmentStatus: 'fulfilled', status: 'shipped',
    shippingAddress: '88, Sector 18, Noida 201301', notes: '',
  },
  {
    id: 'ord_004', orderNumber: 'SP-2409-004', customerName: 'Sneha Reddy', customerEmail: 'sneha.r@design.co', customerPhone: '+91 65432 10987',
    date: '2024-09-19T16:20:00Z',
    items: [
      { id: 'oi_006', productId: 'prod_002', productName: 'A4 Flyers & Leaflets', sku: 'SP-FL-001-130', quantity: 20, unitPrice: 299, total: 5980, image: '' },
      { id: 'oi_007', productId: 'prod_006', productName: 'Tri-Fold Brochures', sku: 'SP-BR-001-170', quantity: 10, unitPrice: 599, total: 5990, image: '' },
    ],
    itemCount: 30, subtotal: 11970, tax: 2155, shipping: 149, discount: 0, total: 14274,
    paymentStatus: 'paid', fulfillmentStatus: 'fulfilled', status: 'delivered',
    shippingAddress: '23, Jubilee Hills, Hyderabad 500033', notes: 'Corporate event materials',
  },
  {
    id: 'ord_005', orderNumber: 'SP-2409-005', customerName: 'Vikram Singh', customerEmail: 'vikram.s@law.firm', customerPhone: '+91 54321 09876',
    date: '2024-09-18T09:00:00Z',
    items: [
      { id: 'oi_008', productId: 'prod_014', productName: 'Business Envelopes', sku: 'SP-EN-001-DL', quantity: 5, unitPrice: 399, total: 1995, image: '' },
      { id: 'oi_009', productId: 'prod_016', productName: 'Duplicate Bill Books', sku: 'SP-BB-001-DUP', quantity: 10, unitPrice: 349, total: 3490, image: '' },
    ],
    itemCount: 15, subtotal: 5485, tax: 987, shipping: 99, discount: 0, total: 6571,
    paymentStatus: 'paid', fulfillmentStatus: 'fulfilled', status: 'delivered',
    shippingAddress: '7, Lajpat Nagar, New Delhi 110024', notes: '',
  },
  {
    id: 'ord_006', orderNumber: 'SP-2409-006', customerName: 'Meera Joshi', customerEmail: 'meera.j@cafe.in', customerPhone: '+91 43210 98765',
    date: '2024-09-17T12:30:00Z',
    items: [
      { id: 'oi_010', productId: 'prod_003', productName: 'Vinyl Banners', sku: 'SP-VB-001-6x3', quantity: 2, unitPrice: 2999, total: 5998, image: '' },
      { id: 'oi_011', productId: 'prod_011', productName: 'Retractable Standees', sku: 'SP-SD-001-3x6', quantity: 3, unitPrice: 1299, total: 3897, image: '' },
    ],
    itemCount: 5, subtotal: 9895, tax: 1781, shipping: 399, discount: 990, total: 11085,
    paymentStatus: 'paid', fulfillmentStatus: 'unfulfilled', status: 'pending',
    shippingAddress: '56, Park Street, Kolkata 700016', notes: 'New cafe opening. Need by Sept 25.',
  },
  {
    id: 'ord_007', orderNumber: 'SP-2409-007', customerName: 'Arjun Mehta', customerEmail: 'arjun.m@corp.com', customerPhone: '+91 32109 87654',
    date: '2024-09-16T15:45:00Z',
    items: [
      { id: 'oi_012', productId: 'prod_010', productName: 'Branded Notebooks', sku: 'SP-NB-001-HB', quantity: 100, unitPrice: 249, total: 24900, image: '' },
      { id: 'oi_013', productId: 'prod_013', productName: 'Custom Ceramic Mugs', sku: 'SP-MP-001-WHT', quantity: 50, unitPrice: 299, total: 14950, image: '' },
    ],
    itemCount: 150, subtotal: 39850, tax: 7173, shipping: 599, discount: 3985, total: 43637,
    paymentStatus: 'paid', fulfillmentStatus: 'partial', status: 'processing',
    shippingAddress: '101, BKC, Mumbai 400051', notes: 'Corporate gifts for annual event. Notebooks ready, mugs pending.',
  },
  {
    id: 'ord_008', orderNumber: 'SP-2409-008', customerName: 'Kavitha Nair', customerEmail: 'kavitha@boutique.in', customerPhone: '+91 21098 76543',
    date: '2024-09-15T11:00:00Z',
    items: [
      { id: 'oi_014', productId: 'prod_022', productName: 'Hang Tags', sku: 'SP-HT-001-ART', quantity: 50, unitPrice: 249, total: 12450, image: '' },
      { id: 'oi_015', productId: 'prod_008', productName: 'Custom Packaging Boxes', sku: 'SP-PB-001-3P-1C', quantity: 20, unitPrice: 2499, total: 49980, image: '' },
    ],
    itemCount: 70, subtotal: 62430, tax: 11237, shipping: 799, discount: 6243, total: 68223,
    paymentStatus: 'pending', fulfillmentStatus: 'unfulfilled', status: 'pending',
    shippingAddress: '33, Anna Salai, Chennai 600002', notes: 'New clothing line launch. Need premium quality.',
  },
  {
    id: 'ord_009', orderNumber: 'SP-2409-009', customerName: 'Rahul Gupta', customerEmail: 'rahul.g@events.co', customerPhone: '+91 10987 65432',
    date: '2024-09-14T09:15:00Z',
    items: [
      { id: 'oi_016', productId: 'prod_017', productName: 'Posters (A3/A2/A1)', sku: 'SP-PS-001-A2-MAT', quantity: 50, unitPrice: 349, total: 17450, image: '' },
    ],
    itemCount: 50, subtotal: 17450, tax: 3141, shipping: 199, discount: 1745, total: 19045,
    paymentStatus: 'paid', fulfillmentStatus: 'fulfilled', status: 'delivered',
    shippingAddress: '78, Koregaon Park, Pune 411001', notes: '',
  },
  {
    id: 'ord_010', orderNumber: 'SP-2409-010', customerName: 'Ananya Das', customerEmail: 'ananya@startup.tech', customerPhone: '+91 09876 54321',
    date: '2024-09-13T14:00:00Z',
    items: [
      { id: 'oi_017', productId: 'prod_001', productName: 'Premium Business Cards', sku: 'SP-BC-001-STD-UV', quantity: 3, unitPrice: 699, total: 2097, image: '/images/cat-business-cards.jpg' },
      { id: 'oi_018', productId: 'prod_023', productName: 'PVC ID Cards', sku: 'SP-ID-001-STD', quantity: 50, unitPrice: 149, total: 7450, image: '' },
    ],
    itemCount: 53, subtotal: 9547, tax: 1718, shipping: 99, discount: 0, total: 11364,
    paymentStatus: 'failed', fulfillmentStatus: 'unfulfilled', status: 'cancelled',
    shippingAddress: '12, Indiranagar, Bangalore 560038', notes: 'Payment failed — customer contacted',
  },
  {
    id: 'ord_011', orderNumber: 'SP-2409-011', customerName: 'Deepak Chopra', customerEmail: 'deepak@food.brand', customerPhone: '+91 98123 45678',
    date: '2024-09-12T10:30:00Z',
    items: [
      { id: 'oi_019', productId: 'prod_012', productName: 'Bottle Labels', sku: 'SP-BL-001-VIN', quantity: 100, unitPrice: 449, total: 44900, image: '' },
      { id: 'oi_020', productId: 'prod_018', productName: 'Custom Paper Bags', sku: 'SP-CPB-001-KFT-M', quantity: 50, unitPrice: 799, total: 39950, image: '' },
    ],
    itemCount: 150, subtotal: 84850, tax: 15273, shipping: 499, discount: 8485, total: 92137,
    paymentStatus: 'paid', fulfillmentStatus: 'fulfilled', status: 'delivered',
    shippingAddress: '45, Hauz Khas, New Delhi 110016', notes: 'Food brand packaging — reorder expected monthly',
  },
  {
    id: 'ord_012', orderNumber: 'SP-2409-012', customerName: 'Pooja Kapoor', customerEmail: 'pooja@wedding.planner', customerPhone: '+91 87234 56789',
    date: '2024-09-11T08:00:00Z',
    items: [
      { id: 'oi_021', productId: 'prod_007', productName: 'Luxury Wedding Cards', sku: 'SP-WC-001-ROY-SLV', quantity: 10, unitPrice: 2499, total: 24990, image: '' },
    ],
    itemCount: 10, subtotal: 24990, tax: 4498, shipping: 299, discount: 2499, total: 27288,
    paymentStatus: 'refunded', fulfillmentStatus: 'returned', status: 'refunded',
    shippingAddress: '9, Civil Lines, Jaipur 302006', notes: 'Client changed wedding date. Full refund processed.',
  },
];

// --- Customers ---

export const MOCK_CUSTOMERS: AdminCustomer[] = [
  { id: 'cust_001', name: 'Rajesh Sharma', email: 'rajesh.sharma@example.com', phone: '+91 98765 43210', totalOrders: 12, totalSpent: 45600, lastOrderDate: '2024-09-22T08:30:00Z', status: 'active', createdAt: '2023-06-15T10:00:00Z', address: '42, Connaught Place, New Delhi 110001', avatar: null },
  { id: 'cust_002', name: 'Priya Patel', email: 'priya.patel@company.in', phone: '+91 87654 32109', totalOrders: 8, totalSpent: 78450, lastOrderDate: '2024-09-21T14:15:00Z', status: 'active', createdAt: '2023-08-20T09:00:00Z', address: '15, MG Road, Bangalore 560001', avatar: null },
  { id: 'cust_003', name: 'Amit Kumar', email: 'amit.k@startup.io', phone: '+91 76543 21098', totalOrders: 15, totalSpent: 62300, lastOrderDate: '2024-09-20T10:45:00Z', status: 'active', createdAt: '2023-04-10T08:00:00Z', address: '88, Sector 18, Noida 201301', avatar: null },
  { id: 'cust_004', name: 'Sneha Reddy', email: 'sneha.r@design.co', phone: '+91 65432 10987', totalOrders: 6, totalSpent: 34200, lastOrderDate: '2024-09-19T16:20:00Z', status: 'active', createdAt: '2024-01-05T10:00:00Z', address: '23, Jubilee Hills, Hyderabad 500033', avatar: null },
  { id: 'cust_005', name: 'Vikram Singh', email: 'vikram.s@law.firm', phone: '+91 54321 09876', totalOrders: 20, totalSpent: 89700, lastOrderDate: '2024-09-18T09:00:00Z', status: 'active', createdAt: '2023-02-28T09:00:00Z', address: '7, Lajpat Nagar, New Delhi 110024', avatar: null },
  { id: 'cust_006', name: 'Meera Joshi', email: 'meera.j@cafe.in', phone: '+91 43210 98765', totalOrders: 3, totalSpent: 15800, lastOrderDate: '2024-09-17T12:30:00Z', status: 'active', createdAt: '2024-05-12T08:00:00Z', address: '56, Park Street, Kolkata 700016', avatar: null },
  { id: 'cust_007', name: 'Arjun Mehta', email: 'arjun.m@corp.com', phone: '+91 32109 87654', totalOrders: 25, totalSpent: 234500, lastOrderDate: '2024-09-16T15:45:00Z', status: 'active', createdAt: '2022-11-01T10:00:00Z', address: '101, BKC, Mumbai 400051', avatar: null },
  { id: 'cust_008', name: 'Kavitha Nair', email: 'kavitha@boutique.in', phone: '+91 21098 76543', totalOrders: 4, totalSpent: 128900, lastOrderDate: '2024-09-15T11:00:00Z', status: 'active', createdAt: '2024-03-15T08:00:00Z', address: '33, Anna Salai, Chennai 600002', avatar: null },
  { id: 'cust_009', name: 'Deepak Chopra', email: 'deepak@food.brand', phone: '+91 98123 45678', totalOrders: 18, totalSpent: 456000, lastOrderDate: '2024-09-12T10:30:00Z', status: 'active', createdAt: '2023-01-10T10:00:00Z', address: '45, Hauz Khas, New Delhi 110016', avatar: null },
  { id: 'cust_010', name: 'Ananya Das', email: 'ananya@startup.tech', phone: '+91 09876 54321', totalOrders: 1, totalSpent: 0, lastOrderDate: '2024-09-13T14:00:00Z', status: 'inactive', createdAt: '2024-09-10T08:00:00Z', address: '12, Indiranagar, Bangalore 560038', avatar: null },
];

// --- Discounts ---

export const MOCK_DISCOUNTS: AdminDiscount[] = [
  { id: 'disc_001', code: 'WELCOME15', type: 'percentage', value: 15, usageCount: 234, usageLimit: 500, minOrderAmount: 999, startDate: '2024-01-01T00:00:00Z', endDate: '2024-12-31T23:59:59Z', status: 'active', applicableTo: 'all' },
  { id: 'disc_002', code: 'BULK20', type: 'percentage', value: 20, usageCount: 89, usageLimit: 200, minOrderAmount: 5000, startDate: '2024-06-01T00:00:00Z', endDate: '2024-12-31T23:59:59Z', status: 'active', applicableTo: 'all' },
  { id: 'disc_003', code: 'WEDDING500', type: 'fixed', value: 500, usageCount: 45, usageLimit: 100, minOrderAmount: 3000, startDate: '2024-03-01T00:00:00Z', endDate: '2024-11-30T23:59:59Z', status: 'active', applicableTo: 'specific' },
  { id: 'disc_004', code: 'FESTIVE25', type: 'percentage', value: 25, usageCount: 567, usageLimit: 500, minOrderAmount: 1500, startDate: '2024-08-15T00:00:00Z', endDate: '2024-09-15T23:59:59Z', status: 'expired', applicableTo: 'all' },
  { id: 'disc_005', code: 'FLAT200', type: 'fixed', value: 200, usageCount: 0, usageLimit: null, minOrderAmount: 1000, startDate: '2024-10-01T00:00:00Z', endDate: null, status: 'disabled', applicableTo: 'all' },
  { id: 'disc_006', code: 'FIRST10', type: 'percentage', value: 10, usageCount: 1245, usageLimit: null, minOrderAmount: 499, startDate: '2024-01-01T00:00:00Z', endDate: null, status: 'active', applicableTo: 'all' },
];

// --- Dashboard Stats ---

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalRevenue: 2847500,
  revenueChange: 12.5,
  totalOrders: 342,
  ordersChange: -1.4,
  totalProducts: 25,
  productsChange: 4.2,
  totalCustomers: 1890,
  customersChange: 8.7,
  averageOrderValue: 8325,
  aovChange: 3.1,
  conversionRate: 4.2,
  conversionChange: 0.8,
};

// --- Analytics ---

export const MOCK_ANALYTICS: AnalyticsData = {
  revenueByMonth: [
    { month: 'Apr', revenue: 185000, orders: 24 },
    { month: 'May', revenue: 210000, orders: 28 },
    { month: 'Jun', revenue: 245000, orders: 31 },
    { month: 'Jul', revenue: 230000, orders: 29 },
    { month: 'Aug', revenue: 310000, orders: 42 },
    { month: 'Sep', revenue: 340000, orders: 45 },
  ],
  topProducts: [
    { name: 'Premium Business Cards', revenue: 345000, orders: 156 },
    { name: 'Luxury Wedding Cards', revenue: 289000, orders: 48 },
    { name: 'Custom Die-Cut Stickers', revenue: 234000, orders: 178 },
    { name: 'A4 Flyers & Leaflets', revenue: 198000, orders: 220 },
    { name: 'Vinyl Banners', revenue: 178000, orders: 45 },
  ],
  topCategories: [
    { name: 'Business Printing', revenue: 680000, percentage: 28 },
    { name: 'Labels & Stickers', revenue: 420000, percentage: 18 },
    { name: 'Marketing Materials', revenue: 380000, percentage: 16 },
    { name: 'Outdoor Advertising', revenue: 340000, percentage: 14 },
    { name: 'Wedding & Events', revenue: 290000, percentage: 12 },
  ],
  customerGrowth: [
    { month: 'Apr', newCustomers: 45, returning: 120 },
    { month: 'May', newCustomers: 52, returning: 135 },
    { month: 'Jun', newCustomers: 48, returning: 142 },
    { month: 'Jul', newCustomers: 55, returning: 155 },
    { month: 'Aug', newCustomers: 68, returning: 170 },
    { month: 'Sep', newCustomers: 72, returning: 185 },
  ],
};

// --- Finance ---

export const MOCK_FINANCE_SUMMARY: FinanceSummary = {
  totalRevenue: 2847500,
  netSales: 2418375,
  totalRefunds: 142375,
  totalTax: 512550,
  totalPayouts: 2100000,
  pendingPayouts: 318375,
};

export const MOCK_FINANCE_TRANSACTIONS: FinanceTransaction[] = [
  { id: 'txn_001', date: '2024-09-22T08:30:00Z', type: 'sale', description: 'Order SP-2409-001 — Rajesh Sharma', amount: 2101, status: 'completed', reference: 'SP-2409-001' },
  { id: 'txn_002', date: '2024-09-21T14:15:00Z', type: 'sale', description: 'Order SP-2409-002 — Priya Patel', amount: 11493, status: 'completed', reference: 'SP-2409-002' },
  { id: 'txn_003', date: '2024-09-20T10:45:00Z', type: 'sale', description: 'Order SP-2409-003 — Amit Kumar', amount: 14841, status: 'completed', reference: 'SP-2409-003' },
  { id: 'txn_004', date: '2024-09-19T16:20:00Z', type: 'sale', description: 'Order SP-2409-004 — Sneha Reddy', amount: 14274, status: 'completed', reference: 'SP-2409-004' },
  { id: 'txn_005', date: '2024-09-18T09:00:00Z', type: 'sale', description: 'Order SP-2409-005 — Vikram Singh', amount: 6571, status: 'completed', reference: 'SP-2409-005' },
  { id: 'txn_006', date: '2024-09-17T12:30:00Z', type: 'sale', description: 'Order SP-2409-006 — Meera Joshi', amount: 11085, status: 'pending', reference: 'SP-2409-006' },
  { id: 'txn_007', date: '2024-09-16T15:45:00Z', type: 'sale', description: 'Order SP-2409-007 — Arjun Mehta', amount: 43637, status: 'completed', reference: 'SP-2409-007' },
  { id: 'txn_008', date: '2024-09-15T00:00:00Z', type: 'payout', description: 'Weekly payout — Sept W3', amount: -125000, status: 'completed', reference: 'PAY-W3-SEP' },
  { id: 'txn_009', date: '2024-09-12T10:30:00Z', type: 'sale', description: 'Order SP-2409-011 — Deepak Chopra', amount: 92137, status: 'completed', reference: 'SP-2409-011' },
  { id: 'txn_010', date: '2024-09-11T08:00:00Z', type: 'refund', description: 'Refund for SP-2409-012 — Pooja Kapoor', amount: -27288, status: 'completed', reference: 'SP-2409-012' },
  { id: 'txn_011', date: '2024-09-08T00:00:00Z', type: 'payout', description: 'Weekly payout — Sept W2', amount: -118000, status: 'completed', reference: 'PAY-W2-SEP' },
  { id: 'txn_012', date: '2024-09-01T00:00:00Z', type: 'payout', description: 'Weekly payout — Sept W1', amount: -95000, status: 'completed', reference: 'PAY-W1-SEP' },
];

// --- Marketing Campaigns ---

export const MOCK_CAMPAIGNS: MarketingCampaign[] = [
  { id: 'camp_001', name: 'Festive Season Sale', type: 'promotion', status: 'active', startDate: '2024-09-15T00:00:00Z', endDate: '2024-10-15T23:59:59Z', reach: 12500, clicks: 3200, conversions: 145, revenue: 234000, budget: 25000 },
  { id: 'camp_002', name: 'Business Cards — LinkedIn', type: 'social', status: 'active', startDate: '2024-09-01T00:00:00Z', endDate: '2024-09-30T23:59:59Z', reach: 45000, clicks: 5600, conversions: 89, revenue: 67800, budget: 15000 },
  { id: 'camp_003', name: 'Wedding Season Email Blast', type: 'email', status: 'completed', startDate: '2024-08-01T00:00:00Z', endDate: '2024-08-31T23:59:59Z', reach: 8500, clicks: 2100, conversions: 62, revenue: 189000, budget: 5000 },
  { id: 'camp_004', name: 'New Product Launch — Neon Signs', type: 'email', status: 'draft', startDate: '2024-10-01T00:00:00Z', endDate: null, reach: 0, clicks: 0, conversions: 0, revenue: 0, budget: 8000 },
  { id: 'camp_005', name: 'Bulk Order SMS Campaign', type: 'sms', status: 'paused', startDate: '2024-09-10T00:00:00Z', endDate: '2024-09-30T23:59:59Z', reach: 3200, clicks: 890, conversions: 23, revenue: 45600, budget: 3000 },
];

// --- Content ---

export const MOCK_CONTENT: ContentPage[] = [
  { id: 'cnt_001', title: 'About Star Press', slug: 'about', type: 'page', status: 'published', updatedAt: '2024-09-15T10:00:00Z', author: 'Admin', views: 4500 },
  { id: 'cnt_002', title: 'Privacy Policy', slug: 'privacy', type: 'page', status: 'published', updatedAt: '2024-08-01T10:00:00Z', author: 'Admin', views: 1200 },
  { id: 'cnt_003', title: 'Terms & Conditions', slug: 'terms', type: 'page', status: 'published', updatedAt: '2024-08-01T10:00:00Z', author: 'Admin', views: 980 },
  { id: 'cnt_004', title: '10 Business Card Design Trends for 2024', slug: 'business-card-trends-2024', type: 'blog', status: 'published', updatedAt: '2024-09-10T10:00:00Z', author: 'Admin', views: 2340 },
  { id: 'cnt_005', title: 'How to Choose the Right Paper for Printing', slug: 'paper-guide', type: 'blog', status: 'published', updatedAt: '2024-08-20T10:00:00Z', author: 'Admin', views: 1890 },
  { id: 'cnt_006', title: 'Wedding Stationery Guide', slug: 'wedding-guide', type: 'blog', status: 'draft', updatedAt: '2024-09-18T10:00:00Z', author: 'Admin', views: 0 },
  { id: 'cnt_007', title: 'Festive Season Sale Banner', slug: 'festive-banner', type: 'banner', status: 'published', updatedAt: '2024-09-12T10:00:00Z', author: 'Admin', views: 8900 },
  { id: 'cnt_008', title: 'Best Sellers Collection', slug: 'best-sellers', type: 'collection', status: 'published', updatedAt: '2024-09-05T10:00:00Z', author: 'Admin', views: 12400 },
  { id: 'cnt_009', title: 'Corporate Essentials Collection', slug: 'corporate-essentials', type: 'collection', status: 'published', updatedAt: '2024-07-15T10:00:00Z', author: 'Admin', views: 5600 },
  { id: 'cnt_010', title: 'Main Navigation', slug: 'main-nav', type: 'navigation', status: 'published', updatedAt: '2024-09-01T10:00:00Z', author: 'Admin', views: 0 },
];
